Ot127 53/feat/componente slider para home
alkemyTech/OT127-CLIENT pull request #10
Opened 2022-01-22 17:54 UTC by solismatias

### Tarea:
Se deberá crear un componente Carrusel que renderice los Slides para la pagína de "Inicio", con la finalidad de detallar información sobre la ONG
La información se mostrára de forma dinámica obtenida del endpoint de slides. Inicialmente, estos datos serán obtenidos de un array de objetos con las propiedades: image, title y description.
El componente deberá contener botones a la derecha e izquierda, para realizar la acción de cambiar la información al siguiente o al anterior slide.
La información de los slides deberá cambiar automaticamente a los 5 segundos para mostrar el siguiente slide.
El componente debe ser totalmente responsive

### Evidencia:
![prueba2](https://user-images.githubusercontent.com/67497671/150602461-8f014103-e60c-461e-bbd2-a73a9bc88b41.png)
![prueba](https://user-images.githubusercontent.com/67497671/150602472-47b11f8d-6c03-4e60-b9ba-d0354429304b.png)

Aclaracion:
los endpoints de slider con el texto de la descipcion vienen con tags, esto no es error en el codigo
![api](https://user-images.githubusercontent.com/67497671/150602475-233f1167-d0f8-4c55-ac49-064232feb978.png)

Renombrado la rama de OT127-53/Feat/SliderHome  a  =>  OT127-53/Feat/componente-slider-para-home

2022-01-22 18:25 UTC, FlaviaCohen requested changes

2022-01-22 18:25 UTC, FlaviaCohen commented on src/Components/Slides/SliderHome.scss
> +// }
Si este código ya no se va a usar, borralo.

2022-01-22 18:28 UTC, FlaviaCohen commented
Solucionar conflictos

2022-01-22 18:38 UTC, solismatias commented on src/Components/Slides/SliderHome.scss
> +// }
Se me habia olvidado! ahi los borré

2022-01-23 17:34 UTC, FlaviaCohen approved these changes

2022-01-23 17:34 UTC, merged