OT127-83/feat/ext-serv-pet
alkemyTech/OT127-CLIENT pull request #108
Opened 2022-02-10 23:22 UTC by nelrodriguez22

2022-02-21 14:47 UTC, FlaviaCohen requested changes

2022-02-21 14:47 UTC, FlaviaCohen commented on src/Components/Backoffice/HomeForm.js
> +        Put('http://ongapi.alkemy.org/api/organization', 1, { name: welcomeText.name, welcome_text: values.welcome })
Si están declaradas las variables de ambiente, usalas

2022-02-21 14:47 UTC, FlaviaCohen commented on src/Components/Backoffice/HomeForm.js
> +        const responseSlides = await Get('http://ongapi.alkemy.org/api/slides')
Misma corrección para todas las urls

2022-02-21 14:47 UTC, FlaviaCohen commented on src/Services/homeApiService.js
> +    //'http://ongapi.alkemy.org/api/activities'
Si tenemos variables de ambiente para proteger la url de la API no la dejamos declarada en un comentario. Podés hacer referencia a que el parámetro "route" es la url de la API

2022-02-21 14:47 UTC, FlaviaCohen commented on src/Services/homeApiService.js
> +    //'http://ongapi.alkemy.org/api/activities' y el ID a eliminar
Mismo comentario

2022-02-21 14:47 UTC, FlaviaCohen commented on src/Services/homeApiService.js
> +    //'http://ongapi.alkemy.org/api/activities'
Mismo comentario para todas las urls comentadas

2022-02-21 14:47 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    let url = route;
este let url no lo estás usando, no es necesaria esa variable. Y aunque la estuvieras usando no es necesario declarar otra variable.

2022-02-21 14:47 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    const { Authorization, error } = token;
las únicas variables que se declaran en mayúscula son los nombres de las funciones que devuelven componentes. Esta variable Authorization debería empezar con minúscula. Se igual que esto no lo hiciste vos pero se me debe haber pasado en otro PR.

2022-02-23 16:59 UTC, nelrodriguez22 commented on src/Services/privateApiService.js
> +    const { Authorization, error } = token;
@FlaviaCohen por favor recorda que esto viene de la api

2022-02-28 21:33 UTC, closed without merging