Ot127-115/Feat/Integrar leaflet maps
alkemyTech/OT127-CLIENT pull request #110
Opened 2022-02-11 12:22 UTC by davidz1995

Criterios de aceptacion: Al ingresar a la página "Contacto", renderizar un mapa con la posición central en la dirección de la ONG, obtenida desde el estado de la organización. Este mapa deberá utilizar un theme customizado, para agregar estilos al marcador de la posición. Manejar excepeciones mostrando un error en el caso de que las peticiones realizadas tengan un error.

**_Mapa con icono personalizado (Logo de la ONG)_**
![image](https://user-images.githubusercontent.com/55600188/153590554-c25261ac-17be-4ec8-88a5-03c5dbc1695a.png)

**_Mapa con ubicación de mensaje correcto_**
![image](https://user-images.githubusercontent.com/55600188/153590634-101bcdf8-412e-4f8c-a190-ec2c1257cc46.png)

**_Mapa con mensaje de error_**
![image](https://user-images.githubusercontent.com/55600188/153590353-337bc9e2-38e2-4a71-a644-16ac4187677e.png)

2022-02-11 18:44 UTC, FlaviaCohen requested changes

2022-02-11 18:44 UTC, FlaviaCohen commented on example.env
> +<<<<<<< HEAD
Acá hay un conflicto sin resolver

2022-02-11 19:05 UTC, davidz1995 commented on example.env
> +<<<<<<< HEAD
Solucionado

2022-02-12 00:27 UTC, FlaviaCohen requested changes

2022-02-12 00:27 UTC, FlaviaCohen commented on src/features/leaflet/Leaflet.jsx
> +        style={{ height: "50vh", width: "50%" }}
Este estilo inline es porque la librerìa solo lo recibe así? No recibe un className?

2022-02-13 18:43 UTC, closed without merging