Ot127 114/feat/router separation
alkemyTech/OT127-CLIENT pull request #121
Opened 2022-02-13 17:37 UTC by Chriscaracach

- Moved backoffice routes to backoffice.js
- Test every route looking at sitemap
- Added "exact" attribute to routes which need it
- Added comments with problems in each component

2022-02-13 18:32 UTC, FlaviaCohen requested changes

2022-02-13 18:32 UTC, FlaviaCohen commented on src/App.js
> +          {/* PROBLEMA El componente activities no muestra ningun listado */}
Hay que verlo con gabi, él es el que hizo ese componente.

2022-02-13 18:32 UTC, FlaviaCohen commented on src/App.js
>    return (
Vas a tener que traerte los cambios de Mauricio y solucionar conflictos ya que él aplicó lazy loading a las rutas.

2022-02-13 18:47 UTC, Chriscaracach commented on src/App.js
> +          {/* PROBLEMA El componente activities no muestra ningun listado */}
Si, hice comentarios de todos los componentes que tiraban algun error. Las rutas andan. Ya lo consulto con él

2022-02-13 18:48 UTC, Chriscaracach commented on src/App.js
>    return (
Ok, mergeá primero el de él si lo manda a tiempo. Yo acomodo cuando me traiga sus cambios

2022-02-15 02:24 UTC, FlaviaCohen approved these changes

2022-02-15 02:24 UTC, merged