OT127-133/feat/estructurar componente footer campaña escolar
alkemyTech/OT127-CLIENT pull request #123
Opened 2022-02-13 23:11 UTC by danieldamian09

Estimada, Flavia 

Creado el componente de Footer para Introducirme en la campaña escolar, cree una carpeta dentro de Components que se llama footer, y también cree la hoja de estilos en la carpeta sass dentro de Components se llama  _campanaEscolarFooter.scss

Estas serian las vistas previas: 

Phone:

![localhost_3001_footer_iphone13midnight_portrait](https://user-images.githubusercontent.com/63797901/153779393-73930912-121b-47ff-83ec-e5bbc22644e1.png)

Tablet: 

![localhost_3001_footer (1)_ipad_spacegrey_landscape](https://user-images.githubusercontent.com/63797901/153779402-b3f077b0-342a-44e5-a38f-b73c743e0e17.png)

Desktop:

![localhost_3001_footer (2)_imac2015_front](https://user-images.githubusercontent.com/63797901/153779414-08ce9173-7067-4070-9c47-42e8faf2db42.png)

Smart TV:

![localhost_3001_footer (3)_samsung_d8000_front](https://user-images.githubusercontent.com/63797901/153779425-1596e191-fab6-4ef8-89a2-4d2738d0e9da.png)

2022-02-14 02:34 UTC, FlaviaCohen requested changes

2022-02-14 02:34 UTC, FlaviaCohen commented on src/Components/Footer/CampanaEscolarFooter.js
> +function CampanaEscolarFooter() {
Fijate que el footer ya estaba creado e importado dentro de la carpeta /Campaigns. No es necesario que crees una carpeta nueva.

2022-02-14 02:34 UTC, FlaviaCohen commented on src/sass/components/_campanaEscolarFooter.scss
> +  &__img__logo{
esta clase debería llamarse `.footer__logo`, no es necesario repetir el img pero si lo hacés nombrala así: `.footer__img-logo` porque no se usa doble elemento en el método BEM, sería un nombre compuesto para el elemento.

2022-02-14 02:34 UTC, FlaviaCohen commented on src/sass/components/_campanaEscolarFooter.scss
> +  &__redes__logo{
Misma corrección

2022-02-14 02:34 UTC, FlaviaCohen commented on src/sass/components/_campanaEscolarFooter.scss
> +  &__redes__titulo{
Misma corrección

2022-02-14 02:34 UTC, FlaviaCohen commented on src/sass/components/_campanaEscolarFooter.scss
> +  &__legales__texto{
Misma corrección

2022-02-14 02:34 UTC, FlaviaCohen commented on src/sass/components/_campanaEscolarFooter.scss
> +  @media (min-width: 768px) {
Esto es exactamente lo que les expliqué que no tienen que hacer. Una media query grande y redeclarar las clases adentro. 

La idea no es que haya dos footers diferentes y que uno se vea en mobile y otro desktop sino que sea el mismo footer con estilos diferentes.

2022-02-14 02:34 UTC, FlaviaCohen commented on src/sass/components/_campanaEscolarFooter.scss
> +  @media (min-width: 1440px){
Misma corrección

2022-02-14 02:34 UTC, FlaviaCohen commented on src/sass/components/_campanaEscolarFooter.scss
> +  @media (min-width: 1600px){
Misma corrección

2022-02-14 18:51 UTC, humbertodrc commented
Estimada, Flavia

Correcciones realizadas, elimine la carpeta que cree y migre todo el código al componente de Footer que estaba creado, también realice las respectivas limpiezas en la mediaquery, mil disculpas que metí estilos ahí se me paso, tambie cambie los nombres en las clases que me indicaste por ejemplo las deje así: footer__redes-titulo

2022-02-15 02:46 UTC, FlaviaCohen requested changes

2022-02-15 02:46 UTC, FlaviaCohen commented on src/sass/components/_campaignsSchoolFooter.scss
> +	@media (min-width: 768px) {
Seguimos en la misma humber, la media query debe ir dentro de cada clase a la que quieras aplicarsela. Ejemplo: 

```
.footer {
	&__container {
		background: rgba(183, 190, 201, 0.26);
		display: flex;
		flex-direction: column;
		justify-content: space-evenly;
		align-items: center;
		width: 100%;
		max-width: 1440px;
		height: 300px;
		margin: 0 auto;
		font-family: $roboto;
		@media (min-width: 768px) {
		     flex-direction: row;
		}
		@media (min-width: 1440px) {
		     align-items: flex-start;
		     padding-top: 2rem;
		}
		@media (min-width: 1600px) {
		     align-items: flex-start;
		     padding-top: 2rem;
		}
	}
}
```
Acá te dejo el ejemplo de como quedaría la clase container, tendrías que hacer lo mismo con todas las clases. Parece tedioso pero tiene un porque. 
Imaginate que tenés que modificar el estilo de algun elemento en todas sus resoluciones... tendrías que buscar todos los lugares donde esa clase está declarada y modificar cada una, en cambio si vos tenés la clase declarada una sola vez y dentro de esa clase todas sus media queries correspondientes sabés que ahí está todo el estilo que corresponde a esa clase, no en otros lados y se achica el margen de error, se hace menos tedioso mantener el código, etc.

2022-02-15 02:46 UTC, FlaviaCohen commented on src/sass/components/_campaignsSchoolFooter.scss
> +	&__separador {
Corrección hincha... pero necesaria. 
No hay que mezclar idiomas. Si la palabra que estás buscando es "separador" vas al traductor de google y lo traducís a inglés. Lamentablemente hay palabras que por default se usan en inglés como "header", "footer", etc. y si partimos de esa base hay que respetar ese idioma. 

Misma corrección para todas las clases declaradas en castellano.

2022-02-15 14:13 UTC, humbertodrc commented
Estimada, Flavia

Correcciones realizadas en el cambio del nombre de las clases y agregué el MediaQuery como me indicaste, gracias por ejemplo creo que le entendí mucho y también la dinámica de lo que se quiere lograr con esta metodología, espero que esta vez si esté bien 😄, te hago otra consulta esta forma de armar el CSS y el MediaQuery lo puedo aplicar sin SASS, o si o si tengo que instalar SASS, me refiero para el armado de una simple Landing Page

2022-02-15 18:43 UTC, FlaviaCohen requested changes

2022-02-15 18:43 UTC, FlaviaCohen commented on src/sass/components/_campaignsSchoolFooter.scss
> +	&__web-title {
La idea de anidar estilos en SASS es no repetir código, fijate que tenés repetido varias veces `&__web`, `&__campaign`, `&__network` y `&__legales`. 

No está mal que queden así ya que cada uno es un elemento pero estaría bueno pensar un nombre para no repetir siempre las mismas palabras. Sino la otra es partir ese nombre compuesto y anidar así: 

```
&__web{
    &-title{}
    &-link{}
}
&__campaign{
    &-title{}
    &-link{}
}
&__network{
    &-title{}
    &-logo{}
}
&__legal{
    &-text{}
}
```

2022-02-15 19:58 UTC, danieldamian09 commented
Estimada, Flavia 

Anidada las clases

2022-02-16 02:59 UTC, FlaviaCohen approved these changes

2022-02-16 03:00 UTC, merged