OT127-130/feat/manejar errores del tipo 404
alkemyTech/OT127-CLIENT pull request #125
Opened 2022-02-14 20:08 UTC by silversurferbeats

Usar la funcionalidad que prueba React-Router-Dom para renderizar un componente por defecto cuando la ruta actual no coincide con ninguna ruta del Switch. Este componente debe mostrar un mensaje personalizado de "Página no encontrada".

2022-02-15 02:31 UTC, FlaviaCohen requested changes

2022-02-15 02:31 UTC, FlaviaCohen commented on src/Components/PageNotFound/404styles.scss
> +.conten{
Ojo con esta clase, quisiste llamarla `.content` ? Le falta una t. 

por otro lado content no es un nombre descriptivo ya que todos los componentes pueden tener un `.content`. Si estamos estilando una vista 404 podemos llamarle al bloque `.notFound`

2022-02-15 02:31 UTC, FlaviaCohen commented on src/Components/PageNotFound/404styles.scss
> +    &__img{
estos estilos no se están aplicando porque a la imagen le falta la clase, si te fijás en el JSX no tiene ninguna imagen. Si le ponés una clase no hace falta que uses el selector img

2022-02-15 02:31 UTC, FlaviaCohen commented on src/Components/PageNotFound/NotFound.js
> +            <div class="conten">
Ojo... regla básica de React y JSX, el atributo class no existe, en React es className. 

Se nota que no lo probaste, debería tirarte error.

2022-02-15 16:52 UTC, silversurferbeats commented on src/Components/PageNotFound/404styles.scss
> +.conten{
Corregido a .notFound. Tengo que prestar mas atencion en las descripciones tanto de las clases como de las variables en los componentes..

2022-02-15 16:58 UTC, silversurferbeats commented on src/Components/PageNotFound/404styles.scss
> +    &__img{
corregido en el JSX con una "className"  para identificar los elementos.

2022-02-15 16:59 UTC, silversurferbeats commented on src/Components/PageNotFound/NotFound.js
> +            <div class="conten">
basiquisimo! mala mia.. Corregido! Por alguna razon me tiraba los estilos de todas formas.. rarisimo :/

2022-02-15 17:18 UTC, silversurferbeats commented
Fla dejo Doc con el componente de manejo de errores:
![image](https://user-images.githubusercontent.com/67937686/154112438-d911e8fa-d94a-4907-99ae-4359aa0be380.png)
Un pequeño video para representar animaciones:
https://user-images.githubusercontent.com/67937686/154114005-ce4349f0-1605-4c0f-91ed-4257a663a041.mp4

2022-02-16 02:58 UTC, FlaviaCohen requested changes

2022-02-16 02:58 UTC, FlaviaCohen commented on src/Components/PageNotFound/404styles.scss
> +body{
Este estilo del body no corresponde a la página de notFound, es un estilo general, por ende tiene que estar en un archivo general de estilo ya que va a impactar en el body de toda la web. Si no es eso lo que querés hacer entonces hay que darle un nombre de clase a lo que estés queriendo apuntar.

2022-02-16 02:58 UTC, FlaviaCohen commented on src/Components/PageNotFound/404styles.scss
> +        &__img{
esta clase no existe. Fijate que por como lo estás anidando la clase a la que estás apuntando es `.notFound__imgContent__img`, en el JSX no tenés esa clase

2022-02-16 02:58 UTC, FlaviaCohen commented on src/Components/PageNotFound/NotFound.js
> +                    <div className="notFound__Description">
las clases no se nombran con la primera letra en mayúscula, es convención. debería ser `notFound__description`

2022-02-16 20:05 UTC, silversurferbeats commented on src/Components/PageNotFound/NotFound.js
> +                    <div className="notFound__Description">
correccion en minuscula de las clases.

2022-02-16 20:05 UTC, silversurferbeats commented on src/Components/PageNotFound/404styles.scss
> +        &__img{
agrego correctamente la clase en el JSX.

2022-02-16 20:05 UTC, silversurferbeats commented on src/Components/PageNotFound/404styles.scss
> +body{
retire el body para que no afecte a los estilos generales.

2022-02-17 15:55 UTC, FlaviaCohen requested changes

2022-02-17 15:55 UTC, FlaviaCohen commented on src/Components/PageNotFound/NotFound.js
> +                <div className="notFound__description">
Esta clase description no la estás usando. Si no la usás no es necesaria

2022-02-17 15:55 UTC, FlaviaCohen commented on src/Components/PageNotFound/NotFound.js
> +                    <a href="#" className="notFound__button">SACAME DE AQUI!.</a>
Este botón estaría bueno que redireccione a la home, fijate que para que no recargue la página en vez de usar un tag <a/> podés usar un tag <Link/> de react.

2022-02-18 03:53 UTC, silversurferbeats commented on src/Components/PageNotFound/NotFound.js
> +                <div className="notFound__description">
corregido.

2022-02-18 03:53 UTC, silversurferbeats commented on src/Components/PageNotFound/NotFound.js
> +                    <div className="notFound__Description">
corregido

2022-02-18 03:53 UTC, silversurferbeats commented on src/Components/PageNotFound/NotFound.js
> +                    <a href="#" className="notFound__button">SACAME DE AQUI!.</a>
utilizo Link de React para hacer la redireccion al "/home".

2022-02-18 19:21 UTC, FlaviaCohen approved these changes

2022-02-18 19:22 UTC, FlaviaCohen commented
Solucionar conflictos

2022-02-18 19:38 UTC, silversurferbeats commented
solucion de conflictos.

2022-02-18 19:42 UTC, merged