Ot127 28/feat/formulario edicion creacion categoria
alkemyTech/OT127-CLIENT pull request #13
Opened 2022-01-23 17:47 UTC by danieldamian09

Branch name update

Summary:

Form Creation
Add Yup to validate Form fields
Creating a Reusable Component to Display error Message
Add useLocation hooks to identify which URL the user is in and be able to perform the corresponding actions
Create Schema for validation of all form inputs
Create a function to display the error message in case an image is not attached
Creation of conditional to make the HTTP request in case we are editing or creating
Show input message type submit in case we are editing or creating

2022-01-24 14:43 UTC, FlaviaCohen requested changes

2022-01-24 14:43 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +    const [mesagge, setMesagge] = useState(false);
Message se escribe con doble s y una sola g

2022-01-24 14:43 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +                    console.log(response);
No dejar console.logs en los PRs, en todo caso dejar un comentario `// TODO` si hay lógica pendiente

2022-01-24 14:43 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +        if (urlCurrent === '/create-category') {
Existe un hook que se importa de esta manera: 

`import { useParams } from "react-router"`

En ese caso si la url es la siguiente: `/category/:id` podés tener acceso a ese id con ese hook. Si existe id el método será PUT y en al cargar el formulario habrá que traer la información existe sobre la categoría con un método GET. Si no existe id el formulario será de creación y los campos permanecerán vacíos para luego hacer un POST con la data ingresada por el usuario. 

No sirve realizar esta lógica en el onSubmit porque el formulario debe tener previamente cargada la info si llegará a ser el caso que el usuario quiere editar la categoría.

2022-01-24 14:43 UTC, FlaviaCohen commented
Solucionar conflictos

2022-01-26 22:02 UTC, danieldamian09 commented
Flavia resulta la lógica del componente espero tus comentarios

2022-01-26 22:03 UTC, danieldamian09 commented
Flavia resuelta la logia del componente espero tus cometarios

2022-01-27 03:22 UTC, FlaviaCohen requested changes

2022-01-27 03:22 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +	const [name, setName] = useState("");
Cuando tenemos tantos estados locales para una misma entidad (en este caso el formulario) podemos agrupar esos estados en uno solo de esta manera: 

`const [formValues, setFormValues] = useState({name: '', description: '', message: '', image: ''})`

Para actualizar cada uno de ellos (por ejemplo 'name') lo haríamos de esta manera: 

`setFormValues({...formValues, name: 'Pepe'})`

2022-01-27 03:22 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +		const ApiData = async (id) => {
Esta lógica habría que declararla en una función por fuera del useEffect y dentro de este sólo ejecutarla, de esta forma mantenemos nuestro código limpio y ordenado.

2022-01-27 03:22 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +				.put(`http://ongapi.alkemy.org/api/categories/${id}`, {
2 cosas con respecto a esta línea. 

La primera: formatear con Prettier ya que quedó indentado rarísimo. 
La segunda: estás usando varias veces la misma url, sería mejor declararla en una variable por fuera y llamarla en vez de repetirla.

2022-01-27 03:22 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +				.then(function (response) {
utilicemos arrow functions

2022-01-28 02:03 UTC, FlaviaCohen requested changes

2022-01-28 02:03 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +	const urlApiCategoriesID = `http://ongapi.alkemy.org/api/categories/${id}`;
la idea no es que declares 2 variables porque seguís repitiendo código. Podés declarar una `variable url = 'http://ongapi.alkemy.org/api/categories'` y cuando tenés que agregarle el id hacés esto ``${url} + id``

2022-01-28 02:03 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +	const ApiData = async (id) => {
- El nombre ApiData no es descriptivo, lo llamaría `getCategoryData`. 
- No hace falta que la función reciba como parámetro id ya que la tenés declarada como una variable que está disponible para el componente.

2022-01-28 02:03 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +			setFormValues({name: "", description: "", image: ""});
Ese else no es necesario ya que los valores iniciales son estos, si no entra al if no hay más nada que hacer.

2022-01-28 02:03 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +		ApiData(id);
Si le sacás el else podés poner un condicional acá que sea:
```
if(id){
   getCategoryData()
}
```

2022-01-28 21:58 UTC, danieldamian09 commented
Fla 

Realizada los cambios, tenía una duda con el nombre de la  concatenación de la URL de la API con el, id ya que está una barra "/" y si no la coloco me da error al momento de traerme los datos por el método GET
![Captura de pantalla 2022-01-28 185805](https://user-images.githubusercontent.com/63797901/151627198-f6f12fd7-3494-490d-928c-f9ae486023fb.png)

2022-01-30 15:31 UTC, FlaviaCohen requested changes

2022-01-30 15:31 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +				const {data} = await Axios.get(`${urlApiCategories}/${id}`);
Está bien concatenarlo así

2022-01-30 15:31 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +					name: data.data.name,
Podés desestructurar más para no repetir tanto data.data

Creo que sería algo así: 

```
const {name, description, image} = await axios.get(`${urlApiCategories}/${id}`);

setFormValues({...formValues, name, description, image})
```

2022-01-30 15:31 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +			setTimeout(() => {
Para que estás usando este setTimeout ? Si es para esperar el request es una mala práctica ya que nunca sabemos cuanto puede tardar y esta operación debe ser asincrónica. Si es para un efecto de UI está bien.

2022-01-30 15:31 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +				.then((response) => {
Estas lógicas no deben estar vacías. Tenés que mandarle la info ingresada por el usuario al endpoint correspondiente, lo mismo con el post.

2022-01-31 10:19 UTC, danieldamian09 commented on src/Components/Categories/CategoriesForm.js
> +			setTimeout(() => {
@FlaviaCohen es para mostrar un mensaje en caso de los campos estén incompletos y luego desaparezca ya que las validaciones la hice manualmente

2022-01-31 10:20 UTC, danieldamian09 commented on src/Components/Categories/CategoriesForm.js
> +				const {data} = await Axios.get(`${urlApiCategories}/${id}`);
@FlaviaCohen perfecto

2022-01-31 10:21 UTC, danieldamian09 commented on src/Components/Categories/CategoriesForm.js
> +					name: data.data.name,
@FlaviaCohen cambio realizado con el destructuring

2022-01-31 15:55 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +			setTimeout(() => {
Ah perfecto, es un efecto entonces. Está bien.

2022-01-31 16:00 UTC, FlaviaCohen requested changes

2022-01-31 16:00 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +				const {name, description, image} = await Axios.get(`${urlApiCategories}/${id}`);
Te fijaste que funcione bien esto? me parece que te falta un .data

2022-01-31 16:00 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +				.then((response) => {
No es solamente retornar las respuestas sino que en el caso del post por ejemplo habría que hacer un clear de los campos del formulario.

2022-02-01 00:31 UTC, danieldamian09 commented
Flavia 

Anexo te detallo las correcciones que realice: 

1. Destructuring de la data que recibo de la API por medio del método GET:
![destructuring](https://user-images.githubusercontent.com/63797901/151893326-aa361421-74ed-4009-827a-16b141b0b9c8.png)
2. Mostrar mensajes de error según la respuesta que me dé la API
https://user-images.githubusercontent.com/63797901/151893971-d9fbe74f-07e3-45ad-8e9d-d8deacd7da38.mp4
3. Lógica  para Mostar el mensaje, en caso de tener un error en la respuesta se mostrará el componente de error
![Captura de pantalla 2022-01-31 212052](https://user-images.githubusercontent.com/63797901/151894519-0ed0fb3d-62fa-4da3-bc08-9adccc71351e.png)
4. Registro guardado en la API
![Captura de pantalla 2022-01-31 200859](https://user-images.githubusercontent.com/63797901/151894126-2b67087b-c6ef-4d1b-b273-2a9e44330085.png)
5. Lógica para
![Captura de pantalla 2022-01-31 212430](https://user-images.githubusercontent.com/63797901/151894728-a2edd73c-9c63-498b-92da-0d5e2907b713.png)
 actualizar un registro en caso de tener un error  muestro el componente de error
6. Utilice como criterio para mostrar los mensajes  response.data.error === "No base64 string provided" y response.data.message === "Category saved successfully" ya que la API te puede dar como respuesta estatus 200, pero esto no significa que se actualizó correctamente el registro y que creaste uno 
7. Anexo te envió detalle de una actualización 
https://user-images.githubusercontent.com/63797901/151895148-0784ede8-80b9-4816-a62f-bc43ebc2c10b.mp4
![Captura de pantalla 2022-01-31 205833](https://user-images.githubusercontent.com/63797901/151895164-f22a3488-ba54-4135-a27a-95f22afdcb16.png)
8. Hice un ajuste en el mensaje a mostrar en el componente de error según si se está editando o creando 
![Captura de pantalla 2022-01-31 213108](https://user-images.githubusercontent.com/63797901/151895287-efcd9a59-1494-47f9-a859-7db621529eaa.png)

Quedo atento a tus comentarios

2022-02-01 01:44 UTC, FlaviaCohen requested changes

2022-02-01 01:44 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +		if ([name, description, image].includes("")) {
mmm... está rato ponerle a un array un .includes, además cualquier string va a contener un string vacío. Si lo que querés comprobar es que todos los valores sean strings vacíos tendrías que hacer esto: `if(name === '' && description === '' && image === '')`. 

De todas formas no es un buen manejo del error. Tendrías que validar cada campo por separado, tal vez en el evento onBlur de cada campo (cuando el input pierde foco).

2022-02-01 01:46 UTC, FlaviaCohen commented
Con respecto al punto 2, el mensaje de error lo tenés que mostrar antes que la API te de una respuesta porque si los campos son requeridos no tenés que dejar que el usuario clickee submit.

2022-02-01 12:13 UTC, danieldamian09 commented
@FlaviaCohen 

Buen día, hice las correcciones que me indicaste, cambie la lógica para validar los inputs, y en la petición POST una vez que se va por él  .then limpio los inputs, en el caso de PUT solo retorno la respuesta

2022-02-01 12:16 UTC, danieldamian09 commented on src/Components/Categories/CategoriesForm.js
> +				.then((response) => {
@fla listo realizad la limpieza de los inputs solo en el post

2022-02-01 20:34 UTC, FlaviaCohen approved these changes

2022-02-01 20:34 UTC, merged