OT127-127/feat/crear layout renderizar contenido rutas backoffice
alkemyTech/OT127-CLIENT pull request #132
Opened 2022-02-15 22:31 UTC by danieldamian09

Estimada, Flavia

Lo que hice para esta tarjeta fue sacar el código que había creado Cris y David del BackOffice donde están todas las rutas y crear un componente de Layout con toda esta Lógica y colocarlo encima del Switch, no te anexo pantalla, ya que prácticamente es una migración de la lógica que habían desarrollado los chicos

2022-02-15 22:32 UTC, humbertodrc commented
Probé si tenía conflictos y no me tiro es raro porque toque un componente en común con Cris

2022-02-16 03:11 UTC, FlaviaCohen requested changes

2022-02-16 03:11 UTC, FlaviaCohen commented on src/Components/Backoffice/BackOffice.js
> +      <LayoutBackOffice />
Está raro esto humber, el layout tiene que ser un componente que tenga un header, un footer, en este caso un sidebar también y que reciba children, envuelve a las rutas y dependiendo de la url el contenido del layout cambia pero el header, footer y sidebar siempre es igual. Fijate porfa en el Layout que hizo mati para la web pública, sería similar a eso pero agregandole el sidebar.

2022-02-16 23:47 UTC, danieldamian09 commented
Estimada, Flavia 

Hice unos ajustes en los componentes de Sidebar y BackofficeHeader, estos estaban juntos en el componente de BackOffice, importe la lógica que desarrollaron en el Header para el Sidebar para que estos funcionen en conjunto, pero en componentes separados, una vez que tuve esto pude limpiar mi componente de Layout  y así solo traerme el Sidebar ,  el componente englobara todo lo que está en el Switch de Backoffice y recibirá como Children todas las rutas 

Disculpa un poco el desastre, pero es que tuve que organizar estos componentes para poder mostrarlos de una manera más limpia en el Layout, el componente de Footer para el Backoffice lo estuve buscando en las tarjetas y no lo conseguí

![Captura de pantalla 2022-02-16 204643](https://user-images.githubusercontent.com/63797901/154376646-dbd975da-1d5e-4483-8d61-8bcd15e3c883.png)

![Captura de pantalla 2022-02-16 204700](https://user-images.githubusercontent.com/63797901/154376668-534b1dcb-5adb-485e-8946-a09e26600b9e.png)

2022-02-17 00:07 UTC, danieldamian09 commented
@FlaviaCohen  estuve revisando y tampoco hay un Header como tal según lo que entendí en esta tarjeta, por eso vez que el Layout de backoffice lo engloba un <Sidebar /> y no un Header  

![Captura de pantalla 2022-02-16 210524](https://user-images.githubusercontent.com/63797901/154378555-c86cc023-eac1-4994-8850-86a1e604cd49.png)

2022-02-18 02:49 UTC, FlaviaCohen approved these changes
Solucionar conflictos

2022-02-18 16:59 UTC, danieldamian09 commented
Estimada, Flavia 

Resuelto conflictos

2022-02-18 19:24 UTC, merged