OT127 98/feat/agregar loading alertas actividades
alkemyTech/OT127-CLIENT pull request #133
Opened 2022-02-15 23:13 UTC by danieldamian09

Estimada Flavia 

Según lo conversado me traje el componente de Nel que no estaba en el main ,  agregue el loading y el mensaje de error en caso de que la llamada a la API falle, con el tema de la URL de la API que esta expuesta  me imagino que Gabriel pasa todo esto al reducer 

![Captura de pantalla 2022-02-15 200549](https://user-images.githubusercontent.com/63797901/154165626-cc1430e1-1956-4b34-b7e0-754382259f99.png)

![Captura de pantalla 2022-02-15 200344](https://user-images.githubusercontent.com/63797901/154165641-cf5c1034-871d-43fa-ab4e-8427914b457b.png)

2022-02-16 02:47 UTC, FlaviaCohen requested changes

2022-02-16 02:47 UTC, FlaviaCohen commented on src/Components/Activities/Activity.js
> +import React from "react";
Humber como quedamos con esto al final? Activity y ActivityDetail no son el mismo componente?

2022-02-16 02:47 UTC, FlaviaCohen commented on src/Components/Activities/Detail/ActivityDetail.js
>  const Detail = () => {
Este componente es rarísimo. Para que lo necesitaríamos?

2022-02-17 23:54 UTC, danieldamian09 commented
Estimada Flavia

Según lo conversado  quedamos con estos tres componentes 

**Activities** ("Sacar Mock y hacer logica de Get y agregar logica de Edit, Delete y renderizar en Backoffice")
**ActivitiesForm** ("No lo toque esta correcto")
**ActivitiesList** ("Va en el Front si queda tiempo generar el detalle de activida (donde se muestra una sola actividad)")
**ActivityDetail** ("Este me comentaste si me quedaba tiempo,  ahí lo arme, pero hay que mejorarlo a nivel de elementos HTML y CSS")


1. Componente **Activities** desarrollé las peticiones dentro de componente tanto GET and DELETE, para el PUT en el botón editar mando el usuario al Formulario y se cargan los datos ("lo último del formulario ya estaba desarrollado") y se renderiza en el backoffice  y tiene agregado el Spinner y el mensaje de alerta en caso de que la petición a la API falle

![Captura de pantalla 2022-02-17 202703](https://user-images.githubusercontent.com/63797901/154590659-66a4f7e0-275e-45ee-9e35-948cd56f7347.png)

![Captura de pantalla (913)](https://user-images.githubusercontent.com/63797901/154590348-53eeb68e-2118-4c15-afe3-32f0d62d1292.png)

![Captura de pantalla (914)](https://user-images.githubusercontent.com/63797901/154590623-fd2b5f69-6a6a-4572-9a9a-492400b61ffa.png)

![Captura de pantalla (915)](https://user-images.githubusercontent.com/63797901/154590726-09aad02d-acd8-4e86-bd9c-d124a668a57a.png)

![Captura de pantalla (916)](https://user-images.githubusercontent.com/63797901/154590748-c9bbb502-34d0-41c6-9657-c56aeb352fb7.png)

![Captura de pantalla (917)](https://user-images.githubusercontent.com/63797901/154590795-973cddf1-821a-4da3-8a34-4cb619224052.png)



2. Componente  **ActivitiesList** se muestra del lado del cliente y también le agregué el Spinner y su mensaje de alerta  

![Captura de pantalla (918)](https://user-images.githubusercontent.com/63797901/154590830-34b3d0b2-9239-40a8-9568-07cf4f9777a8.png)

3 Componente **ActivityDetail** este me comentaste si hay tiempo desarrolle la lógica, faltaría darle un poco más de forma, lo que no entiendo es como el usuario llega a este detalle según el ID yo tengo algo desarrollado en otro proyecto pero es así  

![Captura de pantalla 2022-02-17 205221](https://user-images.githubusercontent.com/63797901/154591214-7e22e320-8185-4b25-a000-d8899ff7a6cd.png)

*De seguro tengo bastantes detalles, pero sé que con tu revisión ya puedo dejar esto un poco más limpio para posteriormente hacer el marge

2022-02-18 02:44 UTC, FlaviaCohen requested changes

2022-02-18 02:44 UTC, FlaviaCohen commented on src/Components/Activities/Activities.js
> +const ActivitiesList = () => {
Hagamos que el nombre del componente coincida con el nombre del archivo, sino se hace poco intuitivo. O le ponés "Activities" al componente o llamás "ActivitiesList" al archivo.

2022-02-18 16:44 UTC, danieldamian09 commented on src/Components/Activities/Activities.js
> +const ActivitiesList = () => {
Listo FLa cambiado

2022-02-18 16:46 UTC, danieldamian09 commented
Estimada, Flavia

Realizada las correcciones en el cambio del nombre del componente  y resuelto conflicto

2022-02-18 19:34 UTC, FlaviaCohen approved these changes
Resolver conflictos

2022-02-18 19:48 UTC, danieldamian09 commented
@FlaviaCohen resulto conflictos

2022-02-18 19:59 UTC, FlaviaCohen approved these changes

2022-02-18 19:59 UTC, merged