Ot127 36/feact/formulario contacto
alkemyTech/OT127-CLIENT pull request #14
Opened 2022-01-23 21:20 UTC by danieldamian09

Summary:

- Creating the Contact Form Component
- Adding Formik for the structure
- Adding Yup for validation
- Create logic to validate the phone number

2022-01-24 14:21 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-01-24 14:21 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +    console.log(values)
No dejar console.logs en los PRs, podés poner un comentario de este estilo: 

`// TODO `

Con esto ya sabemos que está pendiente la lógica del Submit

2022-01-24 14:21 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +          nameContact: '',
Les sacaría el "Contact" a estos datos ya que se repite mucho código y no lo hace más descriptivo, si los campos fueran "name, email, phone y message) sería lo mismo.

2022-01-24 14:21 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +          mesaggeContact:''
`message` va con doble s y una sola g

2022-01-24 14:21 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +            >Email:</label>
Instalá "prettier" como les dejé indicado en el canal de buenas prácticas para que el código siempre esté bien indentado

2022-01-24 14:21 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +          <input
Este input es el botón de "submit"? Si es así debería ser un tag `<button/>` y no un `<input/>`

2022-01-24 14:23 UTC, FlaviaCohen commented
El nombre de la branch debe contener "feat" si es un feature nuevo. Fijate que le pusiste "feact". Por ahora dejalo pero para la próxima lo corregimos.

2022-01-24 18:24 UTC, danieldamian09 commented
Flavia correcciones realizadas y pusheadas, no sé si debe hacer algo más, quedo atento a tus comentarios

2022-01-24 20:36 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-01-24 20:36 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +								F<label htmlFor="phone">Teléfono:</label>
Ojo, hay un typo acá, una F de más. Instalaste prettier o indentaste a mano?

2022-01-24 21:25 UTC, danieldamian09 commented
Listo, Flavia eliminada la F y aplicado el formateo con la extensión que me indicaste

2022-01-24 22:08 UTC, danieldamian09 commented
Flavia actualizado a 2 espacios

2022-01-25 00:47 UTC, FlaviaCohen approved these changes

2022-01-25 00:47 UTC, merged