Ot127-132/feat/contenido del componente de estructura
alkemyTech/OT127-CLIENT pull request #146
Opened 2022-02-18 19:39 UTC by silversurferbeats

Criterios de aceptación: El componente debe estar diseñado para visualizarse primero para dispositivos móviles y contener puntos de ruptura para los diferentes tamaños de pantalla. 
debe observar una cantidad regresiva de días restantes desde el momento actual. Se debe calcular cuándo la persona accede a la página de la campaña (no debe ser dinámico).

2022-02-20 02:05 UTC, silversurferbeats commented
Realizo Landing page de la Campaña escolar donde se aprecia la estategia de diseño "Movile First".
-Para moviles:
![image](https://user-images.githubusercontent.com/67937686/154825492-34d73e50-c149-4faa-a61f-2761b74552a5.png)
-Para tablet:
![image](https://user-images.githubusercontent.com/67937686/154825529-1b72a42c-0890-45c8-a22b-4ce3a8ea7306.png)
-Desktop:
![image](https://user-images.githubusercontent.com/67937686/154825551-715757f0-0077-4754-83e7-c5420f0943f1.png)

2022-02-21 01:42 UTC, FlaviaCohen requested changes

2022-02-21 01:42 UTC, FlaviaCohen commented on src/App.js
> +            <Route path='/Landing' component={Landing} />
la ruta landing no es correcta. El componente contenido ya se visualiza en las rutas de /school-campaign y /toys-campaign

2022-02-21 01:42 UTC, FlaviaCohen commented on src/Campaigns/School/Landing.js
> +const Landing = () => {
Este componente no tiene que existir. La tarjeta no pide que crees un componente sino que sólo le des estilo al componente "Contenido" de las campañas

2022-02-21 01:42 UTC, FlaviaCohen commented on src/Campaigns/School/Landing.js
> +                <form className="inputs-container">
Y además las landing no contienen formulario

2022-02-21 01:42 UTC, FlaviaCohen commented on src/sass/components/_landing.scss
> +// .content {
No dejés comentarios de código que ya no se usa en los PRs

2022-02-21 01:42 UTC, FlaviaCohen commented on src/sass/components/_landing.scss
> +.login-container {
Vas a tener que rehacer este estilo aplicado al componente. que va

2022-02-21 16:54 UTC, silversurferbeats commented
volvi a realizar los estilos y el componente especificandome en  el mobile first:
![image](https://user-images.githubusercontent.com/67937686/154997124-9149b300-da5e-4770-aefd-99b87171c3fd.png)

2022-02-21 16:56 UTC, silversurferbeats commented on src/Campaigns/School/Landing.js
> +const Landing = () => {
Corregido en  ./Campaings/Content.js.

2022-02-21 16:57 UTC, silversurferbeats commented on src/App.js
> +            <Route path='/Landing' component={Landing} />
cambio ubicacion a ./Campaings/School/Content.js

2022-02-22 02:35 UTC, FlaviaCohen requested changes

2022-02-22 02:35 UTC, FlaviaCohen commented on src/App.js
> +            <Route path='/school-content' exact component={SchoolContent} />
Gabi esta ruta no va, el contenido ya se ve en la ruta /school-campaign como te indiqué en la corrección anterior. No es necesario que agregues una ruta adicional.

2022-02-22 02:35 UTC, FlaviaCohen commented on src/sass/components/_landing.scss
> +// .content {
No está resuelto

2022-02-22 02:35 UTC, FlaviaCohen commented on src/sass/components/_landing.scss
> +.login-container {
No está resuelto

2022-02-22 02:35 UTC, FlaviaCohen commented on src/sass/pages/_schoolContent.scss
> +@media (max-width: 600px) {
este es el estilo que va? O es el de _landing.scss?

2022-02-22 15:11 UTC, silversurferbeats commented on src/App.js
> +            <Route path='/school-content' exact component={SchoolContent} />
correcto, elimino la ruta.

2022-02-22 15:11 UTC, silversurferbeats commented on src/sass/pages/_schoolContent.scss
> +@media (max-width: 600px) {
Hola Fla, los estilos de "_landing.scss" eran de un componente anterior.. ahora los remplace por "_schoolContent.scss". Por lo que elimine el archivo "_landing.scss".

2022-02-22 16:31 UTC, FlaviaCohen requested changes

2022-02-22 16:31 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +        console.log(formValues);
Acá hay un console.log en members form, que no tiene nada que ver con esta tarjeta además

2022-02-22 16:31 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +        console.log(res);
Otro más

2022-02-22 16:31 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +            console.log(formValues)
Otro más

2022-02-22 16:31 UTC, FlaviaCohen commented on src/sass/pages/_schoolContent.scss
> +@media (max-width: 600px) {
Y porque están dentro de una media query? No hay estilos para desktop? Porque esta media query es solo para mobile. 

Por otro lado la tarea pide que sea mobile first y ya expliqué como hay que declarar los estilos mobile first. Por favor juntate con alguno de tus compañeros para que te explique como se hace.

2022-02-22 23:25 UTC, FlaviaCohen requested changes

2022-02-22 23:25 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +        console.log(res);
esto tampoco

2022-02-22 23:25 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +            console.log(formValues)
esto tampoco

2022-02-23 02:11 UTC, silversurferbeats commented
correccion de "console.log" y solucion de conflictos.

2022-02-23 13:39 UTC, FlaviaCohen approved these changes

2022-02-23 13:40 UTC, FlaviaCohen approved these changes

2022-02-23 13:40 UTC, merged