Ot127-142/Feat/Permitir donaciones regulares
alkemyTech/OT127-CLIENT pull request #150
Opened 2022-02-19 20:52 UTC by davidz1995

COMO: Usuario
QUIERO: Realizar donaciones
PARA: Contribuir a la actividad de la ONG

Criterios de aceptacion: Agregar botón "Donar" en el Header de la web. Tanto el botón como el componente se deben mostrar sólo para usuarios autenticados, que no sean administradores.

**_Ruta con header y no es backoffice_**
![image](https://user-images.githubusercontent.com/55600188/154818613-d1592016-bfcb-4b9c-8ae1-2acabf59baae.png)

![image](https://user-images.githubusercontent.com/55600188/154818665-a2d2f9c0-fbfd-4feb-b3cb-b635cb984ce2.png)

**_Ruta backoffice sin header ni boton para donar_**
![image](https://user-images.githubusercontent.com/55600188/154818644-a7752421-79db-4885-8bbc-c9189f702430.png)

2022-02-19 21:48 UTC, FlaviaCohen requested changes

2022-02-19 21:48 UTC, FlaviaCohen commented on src/Components/Header/Header.js
> +          <button onClick={() => history.push("/donate")}>Donar</button>
En vez de usar un botón con history.push usemos el <Link/> de react.

2022-02-19 21:48 UTC, FlaviaCohen commented on src/Components/Header/Header.js
> +          <button onClick={() => history.push("/donate")}>Donar</button>
Además la idea no es solamente que el botón lo vean los usuarios en el header público sino que si sos usuario administrador no veas el botón. Falta esa validación.

2022-02-19 22:28 UTC, davidz1995 commented on src/Components/Header/Header.js
> +          <button onClick={() => history.push("/donate")}>Donar</button>
Hola Fla, quedó resuelto el primer comentario.

Con respecto al segundo comentario, si está mostrandose el botón solamente en usuarios que no son Admin. Ese header solamente se está mostrando en rutas que no son backoffice.

2022-02-19 22:31 UTC, davidz1995 commented on src/Components/Header/Header.js
> +          <button onClick={() => history.push("/donate")}>Donar</button>
En la última foto que te envié en la descripción, hay una ruta de admin donde se ve que no se muestra ese botón.

2022-02-19 22:58 UTC, FlaviaCohen commented on src/Components/Header/Header.js
> +          <button onClick={() => history.push("/donate")}>Donar</button>
La corrección iba a que el header público tienen que poder verlo tanto admins como usuarios regulares. Lo único que cambia es que el usuario regular ve el botón de donar pero el admin no. 

El header de backoffice nunca lo va a ver un usuario regular pero no tiene anda que ver con esta tarjeta. El tema es en el header público.

2022-02-20 00:46 UTC, davidz1995 commented on src/Components/Header/Header.js
> +          <button onClick={() => history.push("/donate")}>Donar</button>
Ahí agregué esa funcionalidad

2022-02-21 01:45 UTC, FlaviaCohen approved these changes

2022-02-21 14:48 UTC, FlaviaCohen approved these changes

2022-02-21 14:49 UTC, merged