OT127/fix/fix-news-form
alkemyTech/OT127-CLIENT pull request #165
Opened 2022-02-22 21:40 UTC by cardosonicolas

Summary

- Se soluciono problema que no mostraba las categorias en el combobox.
- Se soluciono problema que no permitia la creacion de nuevas noticias.
- Se soluciono problema que las noticias no se creaban con un caterogy_id.
- Se soluciono problema que no permitia la edicion de noticias. 
- Se añadio variables de entornos.
- Se añadio user feedback con sweetAlert.

2022-02-22 23:37 UTC, FlaviaCohen requested changes

2022-02-22 23:37 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +      reader.readURL_CATEGORIESataURL_NEWS(file);
está bien esto? no debería ser `readURL_CATEGORIESdataURL_NEWS(file)`?

2022-02-23 00:50 UTC, cardosonicolas commented on src/Components/News/NewsForm.js
> +      reader.readURL_CATEGORIESataURL_NEWS(file);
Sin querer lo cambie cuando use el ctrl + d para buscar coincidencias. Lo habia arreglado pero me olvidade de pushearlo. La funcion es readAsDataURL(file).

2022-02-27 00:27 UTC, FlaviaCohen approved these changes

2022-02-27 00:28 UTC, merged