Ot127 43/fix/home styles
alkemyTech/OT127-CLIENT pull request #175
Opened 2022-02-24 19:06 UTC by Chriscaracach

Home page styles

- slider

![Captura de pantalla de 2022-02-24 16-03-50](https://user-images.githubusercontent.com/69370931/155590290-85c5ad4b-ffaa-4117-947f-c0bbbeecdaa7.png)

- último evento

![Captura de pantalla de 2022-02-24 16-04-36](https://user-images.githubusercontent.com/69370931/155590374-bd0d3803-a12e-43e4-bfaa-c85b1e9db55b.png)

- novedades

![Captura de pantalla de 2022-02-24 16-05-18](https://user-images.githubusercontent.com/69370931/155590467-052c8ac9-36ea-4cc9-ba0c-28aea4adb656.png)

- Comentarios

![Captura de pantalla de 2022-02-24 16-05-49](https://user-images.githubusercontent.com/69370931/155590527-86099c2f-e400-41d9-b782-50b2de353277.png)

2022-02-26 14:39 UTC, FlaviaCohen requested changes

2022-02-26 14:39 UTC, FlaviaCohen commented on src/sass/components/_card-custom.scss
> +    left: calc(50px / 2);
acá no sería más fácil poner 25px? porque 50px es una medida fija, no es un valor dinámico. Si fuera una variable dinámica tendría sentido.

2022-02-26 16:10 UTC, Chriscaracach commented on src/sass/components/_card-custom.scss
> +    left: calc(50px / 2);
Tiene sentido, es algo que otra persona puso.

2022-02-27 00:21 UTC, FlaviaCohen approved these changes

2022-02-27 00:21 UTC, merged