Creado formulario login, validado con formik
alkemyTech/OT127-CLIENT pull request #2
Opened 2022-01-20 14:15 UTC by davidz1995

- La contraseña debe tener una longitud mínima de 6 caraceteres, y contener al menos un número, una letra y un símbolo (por ejemplo: @#$%).

- Utilizar formik para validar los campos. Al no disponer aún del servicio de peticiones HTTP, solamente almacenar los campos completados en un objeto (para posteriormente enviarlo).

- El email debe tener un formato adecuado

2022-01-20 18:40 UTC, FlaviaCohen requested changes

2022-01-20 18:40 UTC, FlaviaCohen commented on src/App.js
> +      <LoginForm/> {/* Puesto acá solo para probar, no especifica en que ruta va */}
Crear una <Route/> con path="/login" y pasarle este componente.

2022-01-20 18:40 UTC, FlaviaCohen commented on src/Components/Auth/LoginForm.js
> +    const [usersData, setUsersData] = useState([]);
El formulario de login contiene información de 1 sólo usuario, por ende para que el nombre de la variable sea descriptivo debería ser "userData", si la declaramos como "usersData" estamos usando un nombre que genera confusión ya que podría ser un array.

2022-01-20 18:42 UTC, FlaviaCohen commented
Para próximas instancias: Realizar commits atómicos. No commitear todo el trabajo en 1 solo commit, más bien agrupar tareas más pequeñas en commits descriptivos, que se pueda visualizar el progreso del trabajo.

2022-01-21 00:08 UTC, davidz1995 commented on src/App.js
> +      <LoginForm/> {/* Puesto acá solo para probar, no especifica en que ruta va */}
Solucionado

2022-01-21 00:08 UTC, davidz1995 commented on src/Components/Auth/LoginForm.js
> +    const [usersData, setUsersData] = useState([]);
Solucionado

2022-01-21 02:39 UTC, merged