Ot127 29/feat/create-edit-activity
alkemyTech/OT127-CLIENT pull request #21
Opened 2022-01-24 17:54 UTC by cardosonicolas

Summary

- Modificacion del component ActivitiesForm reutilizable para actividad.
- Creacion del componente CreateEditActivities para separar el comportamiento de ActivitiesForm.

2022-01-24 19:51 UTC, FlaviaCohen requested changes

2022-01-24 19:51 UTC, FlaviaCohen commented on src/Containers/Activities/CreateEditActivities.js
> +      <ActivitiesForm
No es necesario que separes el formulario en un componente aparte ya que estás utilizando este componente CreateEditActivities solo para renderizarlo. 

Es preferible que haya un solo componente con todas sus respectivas funciones y métodos y que se llame `ActivitiesForm`. La utilización del hook useParams() está perfecta y ese id es la condición que va a decretar si el formulario va a utilizarse para crear o editar una actividad.

2022-01-24 19:51 UTC, FlaviaCohen commented on src/Containers/Activities/CreateEditActivities.js
> +    axios.get(`http://ongapi.alkemy.org/api/activities/${id}`).then((res) => {
Por el comentario que te hice más abajo este get debería ejecutarse solo si el id existe.

2022-01-24 19:51 UTC, FlaviaCohen commented on src/Containers/Activities/CreateEditActivities.js
> +    setActivity((prevActivity) => ({ ...prevActivity, name: e.target.value }));
acá podés declararlo un poco más simple. Si el estado local inicial es este: 

`const [activity, setActivity] = useState({name: '', description: '', image: ''})`

podés utilizar un sólo método handleChange que reciba dos parámetros, el evento `e` y la key del objeto que quieras actualizar y te quedaría de esta manera: 

```
const handleChange = (e, property) => {
    setActivity({...activity, [property]: e.target.value})
} 
```

De esta manera ahorramos código y no repetimos siempre lo mismo dentro de los handlers

2022-01-24 19:51 UTC, FlaviaCohen commented on src/Containers/Activities/CreateEditActivities.js
> +  const handleSubmitUpdateActivity = (e) => {
Con llamarlo `handleSubmit` es suficiente, el nombre debe ser descriptivo y corto... handleSubmit es un nombre que por convención todos entendemos la función que realiza. 

Y al igual que en las otras correcciones el condicional debe estar dentro del a función. Si id existe realizará un put, sino realizará un post.

2022-01-25 00:03 UTC, cardosonicolas commented on src/Containers/Activities/CreateEditActivities.js
> +      <ActivitiesForm
Los seperare para que ActivitiesForm sea lo mas presenstacional posible y asi lo puedan reutilizar en cualquier parte del app.

2022-01-25 00:03 UTC, cardosonicolas commented on src/Containers/Activities/CreateEditActivities.js
> +    setActivity((prevActivity) => ({ ...prevActivity, name: e.target.value }));
No lo pude hacer de esta forma:

`setActivity((... activity,description: data }));`

porque el handler del CKeditor se ejecuta a la vez que hace la petecion en la API y me estaba pisando los valores cuando se hacia el spreed. Por consistencia hice lo mismo en las demas handlers.

2022-01-25 00:04 UTC, cardosonicolas commented on src/Containers/Activities/CreateEditActivities.js
> +  const handleSubmitUpdateActivity = (e) => {
Lo hice en dos funciones para separar responsabildades y que sea mas declaravito.

2022-01-25 00:21 UTC, cardosonicolas commented on src/Containers/Activities/CreateEditActivities.js
> +    axios.get(`http://ongapi.alkemy.org/api/activities/${id}`).then((res) => {
Buenisimo.

2022-01-25 22:56 UTC, FlaviaCohen commented on src/Containers/Activities/CreateEditActivities.js
> +      <ActivitiesForm
Esta bien pero la tarjeta pedía crear un formulario, no crear una vista entonces si tenés el formulario y nada más no es el momento de separarlo todavía. 

Veremos más adelante si hay más componentes en la vista de Actividades. Por el momento es sólo el formulario

2022-01-25 23:02 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +  }, [id]);
No es necesario pasarle el id como dependencia ya que sólo hay 1 posibilidad cuando cargás el formulario o la vista, el id existe o no existe. No es necesario que el componente quede a la espera de si el id de repente cambia.

2022-01-25 23:02 UTC, FlaviaCohen commented on src/Containers/Activities/CreateEditActivities.js
> +  const handleSubmitUpdateActivity = (e) => {
Si pero en pos de eso agregás lógica en el JSX y eso es una mala práctica. El JSX debe quedar lo más limpio posible por ende debemos pasarle 1 sola función si es posible y el condicional sobre el id hacerlo dentro del handleSubmit.

2022-01-25 23:03 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-01-25 23:22 UTC, cardosonicolas commented on src/Containers/Activities/CreateEditActivities.js
> +  const handleSubmitUpdateActivity = (e) => {
Claro, entiendo.

2022-01-25 23:23 UTC, cardosonicolas commented on src/Components/Activities/ActivitiesForm.js
> +  }, [id]);
Si le saco la id como dependencia me reta react. Se lo saco igual?

2022-01-25 23:31 UTC, FlaviaCohen requested changes

2022-01-25 23:31 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +      axios.put(`http://ongapi.alkemy.org/api/activities/${id}`, {
Podés guardar la url en una variable por fuera del handleSubmit y así no la repetís tantas veces.

2022-01-25 23:31 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +    <form className="form-container" onSubmit={handleSubmit}>
Perfecto, así debería quedar un JSX bien hecho, limpio sin lógica (o con lo menos posible)

2022-01-25 23:33 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +  }, [id]);
Si, va a tirar un warning tipo "it has a missing dependency" pero si lo ponés le estás cambiando la funcionalidad. En este caso no afecta tanto pero en otro archivo te puede llegar a generar error o loops.

2022-01-25 23:49 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-01-25 23:49 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +      });
El array se lo tenés que pasar, pero vacío.

2022-01-25 23:49 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +  }, [id]);
Le tenés que pasar el array vacío

2022-01-25 23:52 UTC, FlaviaCohen requested changes
Resolver conflictos!

2022-01-26 00:22 UTC, FlaviaCohen requested changes

2022-01-26 00:22 UTC, FlaviaCohen commented on src/App.js
> +          {/* <Route path="/" exact component={} />           Esta ruta debe ser para el Home */}
Esto en vez de aceptarlo habría que haberlo borrado. Pusiste "accept both changes", no? Tendrías que haber puesto "accept current" ya que es un comentario que no hace nada y la ruta de Home ya está hecha

2022-01-26 00:22 UTC, FlaviaCohen commented on src/App.js
> +          <Route path="/backoffice/activities/:id" component={ActivitiesForm} />
ActivitiesForm quedó duplicado

2022-01-26 00:22 UTC, FlaviaCohen commented on yarn.lock
>    "version" "7.16.8"
Este archivo no debería estar trackeado por git.
Porfa eliminalo, agregá "yarn.lock" en el archivo .gitignore y hacé un yarn install nuevamente.

2022-01-26 00:31 UTC, cardosonicolas commented on src/App.js
> +          {/* <Route path="/" exact component={} />           Esta ruta debe ser para el Home */}
Creo que si

2022-01-26 00:31 UTC, cardosonicolas commented on yarn.lock
>    "version" "7.16.8"
Listo

2022-01-26 00:31 UTC, cardosonicolas commented on src/App.js
> +          <Route path="/backoffice/activities/:id" component={ActivitiesForm} />
No entiendo.

2022-01-26 00:37 UTC, FlaviaCohen commented on src/App.js
> +          <Route path="/backoffice/activities/:id" component={ActivitiesForm} />
Fijate que la ruta ` <Route path="/backoffice/activities/:id" component={ActivitiesForm} />` está dos veces

2022-01-26 00:40 UTC, FlaviaCohen approved these changes

2022-01-26 00:40 UTC, FlaviaCohen commented on src/App.js
> +          <Route path="/backoffice/activities/:id" component={ActivitiesForm} />
Ah no, perdón. Pensé que había una ruta duplicada pero son rutas diferentes con el mismo componente.

2022-01-26 00:40 UTC, merged

2022-01-26 00:40 UTC, cardosonicolas commented on src/App.js
> +          <Route path="/backoffice/activities/:id" component={ActivitiesForm} />
No lo veo duplicado en mi codigo, borre el unico que tenia para ver si era eso.