Ot127 55/feat/contacto de la ong
alkemyTech/OT127-CLIENT pull request #24
Opened 2022-01-24 23:06 UTC by nelrodriguez22

2022-01-24 23:42 UTC, FlaviaCohen requested changes

2022-01-24 23:42 UTC, FlaviaCohen commented on src/Components/Contact/contact.css
> +.contact {
Cual es la función de este archivo? Si ya tenés el contact.scss?

2022-01-24 23:42 UTC, FlaviaCohen commented on src/Components/Contact/contact.css.map
> +{
Lo mismo con este

2022-01-24 23:46 UTC, nelrodriguez22 commented on src/Components/Contact/contact.css.map
> +{
no se, me los creo automáticamente el vscode, supuse que eran parte del archivo de scss, ahora los saco.

2022-01-25 00:55 UTC, FlaviaCohen requested changes

2022-01-25 00:55 UTC, FlaviaCohen commented on public/libs/ionicons/scss/ionicons.css
> +@charset "UTF-8";
Algo instalaste para los íconos y te generó este archivo. Son necesarios todos estos íconos? Porque son muchísimos.

2022-01-25 00:55 UTC, FlaviaCohen commented on public/libs/ionicons/scss/ionicons.css
> +  content: "";
Y me resulta raro que les falta el código en el content.

2022-01-25 00:55 UTC, FlaviaCohen commented on src/Components/Contact/Contact.js
> +					<Title title="Contacto" />
Estas clases no son descriptivas. El div debería ser `contact__title-container` y el título `contact__title-text`

2022-01-25 00:55 UTC, FlaviaCohen commented on src/Components/Contact/Contact.js
> +					<p>Nombre:{props.name}</p>
Hay que desestructurar estas props para no repetir tanto código.
Podés hacerlo de esta manera: 

`const Contact = ({name, short_description, address, phone, cellphone})`

2022-01-25 00:55 UTC, FlaviaCohen commented on src/Components/Titulosynovedades/Title.js
> +				backgroundImage: `url(${image})`
Ojo que esto está pasando porque hay un lio con la branch de origen. Esta corrección es de la tarea del título y me está apareciendo en la tarea de contacto. 

Asegurate de siempre sacar una branch nueva desde tu branch main local después de haber hecho pull de main remoto

2022-01-25 16:02 UTC, FlaviaCohen requested changes

2022-01-25 16:02 UTC, FlaviaCohen commented on src/Components/Contact/contact.scss
> + .contact__content {
la idea de utilizar sass, clases anidadas y método BEM es no repetir código.

Si la palabra que se repite (el bloque) es `contact` tenés que hacer una clase padre que tenga ese nombre y anidar todo el resto. 

```
.contact{
    &__container{}
    &__title-text{}
    &__content{}
    &__footer
}
```

2022-01-26 00:05 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-01-26 00:05 UTC, FlaviaCohen commented on src/Components/Contact/contact.scss
> +.contact{
Perfecto!

2022-01-27 03:45 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-01-27 03:45 UTC, FlaviaCohen commented on src/App.js
> +					<Route path="/contacto" component={Contact} />
Hay dos rutas para contacto, cual es la que va? /contact o /contacto? No será que el formulario de contacto va dentro de la vista de Contacto? En tal caso no necesitamos otra ruta para el ContactForm sino que lo importes y muestres directamente en la ruta /contact

2022-01-28 02:29 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-01-30 15:42 UTC, FlaviaCohen commented
Solucionar conflictos

2022-01-31 16:37 UTC, FlaviaCohen commented
Resolver conflictos

2022-02-02 16:13 UTC, FlaviaCohen approved these changes

2022-02-02 16:13 UTC, merged