Ot127 57/feat/componentes actividades
alkemyTech/OT127-CLIENT pull request #25
Opened 2022-01-24 23:22 UTC by nelrodriguez22

2022-01-24 23:51 UTC, FlaviaCohen requested changes

2022-01-24 23:51 UTC, FlaviaCohen commented on src/Components/Activities/List.js
> +const List = () => {
List no es un nombre descriptivo ya que todas las secciones de la web van a tener listas... de categorías, de novedades, de usuarios, etc. Le pondría `Activities`

2022-01-24 23:51 UTC, FlaviaCohen commented on src/Components/Activities/List.js
> +			<Title title="Actividades" />
El componente debe ser un listado. Hay que traer la lista de actividades de la API además de mostrar el título. Pero en tu defensa... la tarjeta no lo dice explícitamente. Vos hiciste exactamente lo que la tarjeta dice.

2022-01-25 14:34 UTC, nelrodriguez22 commented on src/Components/Titulosynovedades/Title.js
> -				backgroundImage: `url(${image || imgPlaceHolder})`
Este error se me paso de cuando subi el comp titulo asi que de paso lo corregi

2022-01-26 00:17 UTC, FlaviaCohen requested changes

2022-01-26 00:17 UTC, FlaviaCohen commented on src/Components/Activities/Activities.js
> +	const [ activities, setActivities ] = useState(null)
si activities va a ser un array de actividades debe ser inicializado en el mismo tipo de dato, es decir un array vacío. No se deben mezclar tipos de datos al inicializar estados.

2022-01-26 00:17 UTC, FlaviaCohen commented on src/Components/Activities/Activities.js
> +		axios.get(url)
Esta lógica podés declararla en una función por fuera del useEffect y dentro sólo llamarla así queda más limpio y ordenado.

2022-01-26 00:17 UTC, FlaviaCohen commented on src/Components/Activities/Activities.js
> +				setLoading(true)
Sería al revés. loading debe ser `true` cuando se esté realizando la petición y la página este "cargando".  Por eso cuando declares la función por fuera debería ser algo así: 

```
const getActivities = () => {
    setLoading(true),
    axios.get...
    setLoading(false)
}
```

2022-01-26 00:17 UTC, FlaviaCohen commented on src/Components/Activities/Activities.js
> +				{loading ? activities.data.map(({ id, name, description, image }) => (
Y acá el condicional sería al revés: si loading es `true` voy a mostrar el texto "cargando...", sino voy a mostrar la lista.

2022-01-26 00:17 UTC, FlaviaCohen commented on src/Components/Activities/activities.css
> +* {
Este es un selector general. No debería estar en el estilo de activities sino en una hoja de estilo global.

2022-01-26 00:17 UTC, FlaviaCohen commented on src/Components/Activities/activities.css
> +ul {
Ojo porque con esto vas a darle estilo a todas las listas del proyecto y si esa es la intensión debería estar en una hoja de estilo global

2022-01-26 00:17 UTC, FlaviaCohen commented on src/Components/Titulosynovedades/Title.js
> -				backgroundImage: `url(${image || imgPlaceHolder})`
Bien, la próxima podés hacer una nueva branch con el id de la otra tarjeta y cambias el "Feat" por "Fix".

2022-01-26 00:17 UTC, FlaviaCohen commented on src/Components/Titulosynovedades/title.css
> +.title__header {
Lo mismo con esto, es código de la otra tarjeta.

2022-01-26 00:17 UTC, FlaviaCohen commented
Solucionar conflictos

2022-01-27 03:54 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-01-28 02:31 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-02-03 16:55 UTC, FlaviaCohen approved these changes

2022-02-03 16:55 UTC, merged