Ot127 30/feat/slides form
alkemyTech/OT127-CLIENT pull request #28
Opened 2022-01-25 03:26 UTC by Mauricio-Ojeda

Descripción
COMO: Usuario administrador
QUIERO: Crear o editar un slide existente
PARA: Mantener el contenido actualizado

Criterios de aceptacion: En base del formulario de creación existente que contiene los campos Name, Description y Order, agregar el campo Imagen. Para la Descripción, reemplazar el campo de texto por la librería CKEditor. El objetivo es crear un formulario reutilizable para las acciones de edición como de creación. Para esto, deberá poder recibir un objeto de forma condicional, y comportarse como un formulario de creación o edición según corresponda. En el caso de no recibir el objeto como propiedad, deberá realizar una petición POST al endpoint de creación (/slides/create). En el caso de recibirlo, completar el formulario con los campos del mismo y realizar una petición PATCH al endpoint de actualización del server (/slides/:id). Este formulario se mostrará en el backoffice tanto en las rutas de creación y edición (/backoffice/slides).

Validaciones:

Todos los campos son obligatorios

Name debe tener una longitud mínima de 4 caracteres 

Órder debe ser único

La imagen deberá tener un formato .jpg o .png

2022-01-25 12:21 UTC, FlaviaCohen requested changes

2022-01-25 12:21 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +    const getSlidesData = async () => {
Es más prolijo declarar esta función fuera del useEffect, luego dentro de él sólo la ejecutamos

2022-01-25 12:21 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +    const getSlidesById = async () => {
No es necesario tener 2 useEffect y 2 funciones diferentes. Podés hacer un condicional en el que si existe el id haga un get a la url con el id, y sino que sea sólo un get sin el id. Tampoco necesitamos que ese id esté en el array del useEffect ya que para que ese id cambie significaría que cambiamos de vista, por ende el componente se recarga y no tendría sentido.

2022-01-25 12:21 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +            const { data: status } = res;
Estas desestructuraciones están raras. 

no es necesario cambiar tanto los nombres, si estás recibiendo `res` entonces podés manejarte con res. 

a lo sumo en la lína 52 podés hacer esto: 

`const { name, description, order, image } = data` y así ya no repetís data en cada valor del objeto. Te quedaría asi´: 

```
setInitialValues({
                name,
                description,
                order,
                image,
              })
```

2022-01-25 12:21 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +                order: data.order ? data.order : "",
Cuando el número de orden viene vacío cual es el valor por default que viene? Porque si viene un string vacío no hay necesidad de ponerle este condicional. 

Asumo que viene 0, en este caso es el dato correcto para inicializar una variable de tipo número. No hay que mezclar tipos de dato, si una variable será número lo correcto es inicializarla en 0, si será string pues en un string vacío.

2022-01-25 12:21 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +      const url = `http://ongapi.alkemy.org/api/slides/${id}`;
Esto lo estás usando varias veces, te conviene declarar la constante afuera de las funciones y la tenés disponible para todo lo que quieras usarla

2022-01-25 12:21 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +    } else if (!id) {
No es necesario este else if si la condición es un booleando, el id existe o no existe, es verdadero o falso, entonces manejate con un if y un else, else if lo usamos para cuando tenemos una tercera condición que no es la contraria a la anterior.

2022-01-25 14:32 UTC, Mauricio-Ojeda commented on src/Components/Slides/SlidesForm.js
> +                order: data.order ? data.order : "",
Eso  lo puse porque algunos Slides precargados en al API vienen con order Null, cuando tengamos nuestros slides ya no pasaria eso, igualmente estoy mezclando tipo de datos ahi lo corijo.

2022-01-25 23:24 UTC, FlaviaCohen requested changes

2022-01-25 23:24 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +  const getSlidesById = async (id) => {
Se que es muy puntillosa esta corrección pero si el método devuelve la data de 1 solo slide debería llamarse getSlideById, si lo ponés en plural da la idea de que la función devuelve un array de slides.

2022-01-25 23:24 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +          setInitialValues({
antes de setear los valores podés desestructurar un poco a `res` y no repetir tanto código: 

```
const { name, description, order, image } = res.data.data

setInitialValues({name, description, order, image})
```
Con respecto al dato de order te fijaste como viene cuando no te viene un order? No viene en 0? Porque si es así no hace falta el condicional.

2022-01-25 23:24 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +        .put(`${url}/${id}`, {
El mismo tipo de desestructuración que te marqué antes la podés hacer acá.

Le podés mandar directamente el objeto `formValues` ?

2022-01-25 23:26 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +            const { data: status } = res;
No resuelvo esta conversación porque te dejé un comentario nuevo al respecto.

2022-01-25 23:45 UTC, Mauricio-Ojeda commented on src/Components/Slides/SlidesForm.js
> +        .put(`${url}/${id}`, {
ahi pruebo lo hice asi, porque la api me daba error, y asi poder ver bien cual era el que me tenia conflicto.

2022-01-26 00:36 UTC, FlaviaCohen requested changes

2022-01-26 00:36 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +            name: initialValues ? initialValues.name : "",
En vez de hacer esto probaste declarar el estado local así: 

`const [initialValues, setInitialValues] = useState({name: '', description: '', order: '', image: ''})`

y pasarselo a Formik así: 

`initialValues=(initialValues)`

2022-01-26 00:44 UTC, Mauricio-Ojeda commented on src/Components/Slides/SlidesForm.js
> +            name: initialValues ? initialValues.name : "",
Lo manejo asi para setear los valores iniciales dependiendo de si es de edicion o creacion. initialValues es para cargar los valores de los slides para edicion, y los vacios para creacion. Le puedo cambiar el para que quede mas claro que es lo que quiero hacer le cambio el nombre a initialValuesEdition. Te parece?

2022-01-26 00:45 UTC, Mauricio-Ojeda commented on src/Components/Slides/SlidesForm.js
> +            name: initialValues ? initialValues.name : "",
* Le puedo cambiar el nombre

2022-01-27 03:26 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +            name: initialValues ? initialValues.name : "",
Es que no hace falta porque initialValues siempre va a ser uno solo, la diferencia es que si existe el id esos initialValues van a tener valores y si no existe el id van a ser strings vacíos. Pero no hace falta que tengas estados diferentes.

2022-01-27 03:30 UTC, FlaviaCohen requested changes

2022-01-27 03:30 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +  const getSlidesData = async () => {
Ahora que veo este método, es necesario? que es lo uqe hace? 

La idea es que si el formulario es de creación los inputs inicialmente estén vacíos. No te hace falta un método cuando el id no existe, sólo tenés que mostrar el formulario vacío y hacer un post. 

Si el id existe ahí si hacés un get de slidesData y hacés setInitialValues con la data que te traés de la slide existente.

2022-01-27 03:30 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +    getSlidesData();
o sea... este get no es necesario

2022-01-27 03:31 UTC, Mauricio-Ojeda commented on src/Components/Slides/SlidesForm.js
> +            name: initialValues ? initialValues.name : "",
si hoy cuando vi el codigo me di cuenta que no hacia falta y ya lo corregí.

2022-01-27 03:33 UTC, Mauricio-Ojeda commented on src/Components/Slides/SlidesForm.js
> +  const getSlidesData = async () => {
es porque el numero de order tiene que ser unico y para probarlo necesito traerme todos los slides armo un array de order

2022-01-27 03:41 UTC, Mauricio-Ojeda commented on src/Components/Slides/SlidesForm.js
> +    getSlidesData();
El resultado lo guardo aca
const [slidesData, setSlidesData] = useState([]); // para validar order

Y armo este arreglo que uso para validar que order sea unico
const orderUnique = slidesData
    .map((data) => data.order)
    .filter((order) => order !== initialValues.order);

2022-01-27 21:46 UTC, Mauricio-Ojeda commented on src/Components/Slides/SlidesForm.js
> +  const getSlidesData = async () => {
refactorice el codigo para que sea mas legible y se entienda

2022-01-28 02:11 UTC, FlaviaCohen approved these changes

2022-01-28 02:11 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +    getOrdersList();
Genial!! ahora si tiene más sentido.

2022-01-28 02:11 UTC, merged