FormularioMiembros
alkemyTech/OT127-CLIENT pull request #29
Opened 2022-01-25 13:40 UTC by silversurferbeats

Formulario miembros, validacion de los campos con Formik, agrego CKEditor,

2022-01-25 23:57 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-01-25 23:57 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
>      console.log(initialValues);
No dejemos console.logs en los PRs.
Si querés podés poner un alert para mostrar los datos.

2022-01-25 23:57 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +    function getDataFromTheEditor() {
utilicemos arrow functions

2022-01-25 23:57 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +                    console.log( 'Editor is ready to use!', editor );
No dejemos console.logs en los PRs

2022-02-01 01:58 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-02-01 01:58 UTC, FlaviaCohen commented on src/Components/Members/Members.scss
> +  form {
Este tag va a hacer que todos los formularios tengan este estilo, si esa es la intención debería estar en una hoja de estilos globales.

2022-02-01 01:58 UTC, FlaviaCohen commented on src/Components/Members/Members.scss
> +  $white: white;
Esta variable de sass que hace acá?

2022-02-01 01:58 UTC, FlaviaCohen commented on src/Components/Members/Members.scss
> +  input {
Lo mismo con esto, va a darle estilo a todos los inputs de la web.

2022-02-01 01:58 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
>      console.log(initialValues);
Sigue estando este console.log, no lo dejemos en el PR

2022-02-01 01:58 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +      .create(document.querySelector('#agenda_mesyuarat'))
Esto es una mala práctica, no se usan métodos para manipular el DOM en React

2022-02-01 01:58 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +    function getDataFromTheEditor() {
utilicemos arrow functions

2022-02-01 01:58 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +    function send_1() {
arrow functions

2022-02-01 01:58 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +                    console.log( 'Editor is ready to use!', editor );
Sigue estando el console.log, no los dejemos en el PR

2022-02-03 00:53 UTC, silversurferbeats commented
hola fla, agrego CKEditor y estilos SASS.
![image](https://user-images.githubusercontent.com/67937686/152262907-77f76b4d-20dd-44ac-a34f-23093ba369cd.png)

2022-02-03 14:57 UTC, closed without merging