Ot127 59/feat/Componentes donar y gracias
alkemyTech/OT127-CLIENT pull request #3
Opened 2022-01-20 14:18 UTC by davidz1995

2022-01-20 23:15 UTC, FlaviaCohen commented
Tratá a partir de ahora de realizar commits "atómicos", cada commit debe reflejar un paso de la tarea o englobar pequeñas porciones de código o mini-features. De esta manera en caso de tener que hacer un rollback es más fácil y también puede evidenciarse el progreso del trabajo en esos commits.

2022-01-20 23:18 UTC, FlaviaCohen requested changes

2022-01-20 23:18 UTC, FlaviaCohen commented on src/App.js
> +            render={(props) => (
Sigamos la misma estructura que tienen las demás rutas, en vez de usar "render" usemos component

2022-01-20 23:18 UTC, FlaviaCohen commented on src/Donations/Donacion.jsx
> +function Donacion(props) {
Utilicemos arrow functions de esta manera y desestructuremos props de esta manera (ahorramos código y es convención): 

const Donacion = ({message}) => {
    ...
}

2022-01-20 23:42 UTC, davidz1995 commented on src/Donations/Donacion.jsx
> +function Donacion(props) {
Entendido y solucionado.

2022-01-20 23:56 UTC, davidz1995 commented on src/App.js
> +            render={(props) => (
Hola Fla, acá tengo el problema que en esta versión de react router dom el component recibe solo el nombre del componente a diferencia de las nuevas versiones que tenemos en lugar de component, element y le pasamos un componente directo <Componente/> y acá si le puedo pasar props ahi directamente. 

Como la consigna pide que ese componente pueda recibir props, vi que hay dos maneras de hacerlo, si lo hago con component directamente, se ´puede pero daría el problema de renderizado que detalla la imagen de abajo.

![image](https://user-images.githubusercontent.com/55600188/150440336-741527bd-1b64-4413-9948-f96c26b68f80.png)

La solución que menciona que de react router dom es usar el render y pasarle las props. Dejo adjunto en la siguiente imagen.

![image](https://user-images.githubusercontent.com/55600188/150440856-9f79f6d9-1d45-4ba1-b878-00e322975b5e.png)

En esta situación, lo mantengo en render o lo pongo con component?

2022-01-22 00:35 UTC, davidz1995 commented on src/App.js
> +            render={(props) => (
Hecho el cambio a component en lugar de render.

2022-01-22 15:02 UTC, FlaviaCohen requested changes

2022-01-22 15:02 UTC, FlaviaCohen commented on src/App.js
> +          <Route path='/donar' component={() => (<Donacion message={'Quieres donar?'}/>)}/>
Hiciste un pull de main antes de este push? Porque tus rutas están pisando las de login y register

2022-01-22 15:02 UTC, FlaviaCohen commented on src/Donations/Donacion.jsx
> +        {message &&
No es necesario este condicional

2022-01-22 15:02 UTC, FlaviaCohen commented on src/Donations/Gracias.jsx
> +function Gracias() {
Usemos arrow functions así somos consistentes en todos los archivos.

2022-01-22 15:02 UTC, FlaviaCohen commented on src/App.js
> +import Donacion from './Donations/Donacion';
Hiciste un pull de main antes de este push? Porque tus rutas están pisando las de login y register

2022-01-22 16:36 UTC, closed without merging