Ot127 32/feat/formulario edicion home
alkemyTech/OT127-CLIENT pull request #32
Opened 2022-01-25 21:30 UTC by solismatias

### Tarea:

Criterios de aceptacion: Este formulario permitirá editar el contenido de la página de Inicio. Contendrá un textarea para modificar el texto de Bienvenida (requerido, mínimo de 20 caracteres) y Slides (son 3, cada slide contiene una imagen y un texto).
Este formulario se mostrará en el backoffice (/backoffice/home).

### Evidencia

![localhost_3000_backoffice_home (1)](https://user-images.githubusercontent.com/67497671/151062391-e91f81f3-8e14-4266-af72-06cfadbcf2ab.png)

2022-01-25 23:46 UTC, FlaviaCohen requested changes

2022-01-25 23:46 UTC, FlaviaCohen commented on src/Components/Backoffice/HomeForm.js
> +
Mati no logro entender que quisiste hacer acá.

2022-01-25 23:46 UTC, FlaviaCohen commented on src/Components/Backoffice/HomeForm.js
> +                // solo traemos los 3 primeros slides, de ser necesario traer todos, borrar el "?limit=3"
Si te está complicando el que sean 3 slides traelas todas. De hecho si la api recibe más de 3 slides entonces traelas todas y olvidate del límite de 3. Si el límite fuera 3 la API debería estar preparada para eso.

2022-01-25 23:46 UTC, FlaviaCohen commented on yarn.lock
>    "version" "7.16.8"
El archivo yarn.lock debería estar en el .gitignore

Te pido porfa borres este archivo, lo agregues al archivo .gitignore y hagas un yarn install de nuevo

2022-01-27 03:34 UTC, FlaviaCohen requested changes

2022-01-27 03:34 UTC, FlaviaCohen commented on yarn.lock
>    dependencies:
Sigue apareciendo este archivo, necesito que dentro del archivo .gitignore escribas "yarn.lock", borres este archivo yarn.lock y hagas un yarn install nuevamente

2022-02-01 00:17 UTC, solismatias commented on yarn.lock
>    dependencies:
Ahi lo borre, ya esta dentro del .gitignore, cuando hago el git pull origin main me trae el yarn.lock de vuelta, nose si eso sera problema

2022-02-01 01:53 UTC, FlaviaCohen requested changes

2022-02-01 01:53 UTC, FlaviaCohen commented on src/Components/Backoffice/HomeForm.js
> +
Porfa necesito que me expliques que quisiste hacer acá porque sino no puedo mergear el PR

2022-02-01 01:53 UTC, FlaviaCohen commented on src/Components/Backoffice/HomeForm.js
> +        const getDataToEdit = async () => {
Esta función declarala afuera del useEffect y adentro sólo llamala

2022-02-01 15:22 UTC, solismatias commented on src/Components/Backoffice/HomeForm.js
> +
Perdon! siempre me olvido de responder los comentarios
mejor updateValues la voy a renombrar a compareValues, lo que hace esta funcion es  comparar los datos que traje de la api con los valores que se envian del formulario. 

Por ejemplo el mensaje de bienvenida que vino de la api lo comparo con el mensaje de bienvenida que devuelve el onSubmit, y si son diferentes es que el mensaje se edito y hago la peticion para actualizar

Y para los slides, tengo 2 "if" anidados, primero recorro los slides que traje de la api y los comparo con los slides que devuelve el formulario, el primer "if" compara los id y cuando son los mismos pasan al segundo "if" que este compara si se modificaron los campos "name", "image" y "description" para luego actualizar los datos del slide modificado

2022-02-01 20:39 UTC, FlaviaCohen commented on src/Components/Backoffice/HomeForm.js
> +
Creo que te estás complicando mucho. La api va a recibir un id y campos correspondientes a las slides. No es necesario que hagas toda esa validación, podés mandar los datos como vienen y si no hubo cambios no se va a actualizar nada por más que mandes la info que tienen los campos. Se entiende? 

si yo tengo un slide id = 1 y le mando un put con data {id: 1, text: 'new text', img: 'añslfkdj.png'} y la info es la misma que ya tiene el slide, no va a pasar nada. 

Yo sacaría esa lógica y sólo comprobaría si existe id, si existe hacés un get inicial, seteas los valores como estado inicial local y hacés un put en el onSubmit, si no existe los datos iniciales serán strings vacíos y la petición será post.

2022-02-03 02:18 UTC, solismatias commented on src/Components/Backoffice/HomeForm.js
> +
ahi lo intente, pero surgio un imprevisto, son demaciados slides, mas de 20, entonces tiene que hacer mas de 20 peticiones put y creo que la api no aguanta tantas peticiones de golpe y no se guarda ningun cambio! asi que creo que voy a tener que validar cuales slides fueron modificados y enviar solo esos.
Encontre una solucion mucho mas sencilla a la  que habia usado antes, solo comparo el initialValues con los values que devuelve el formulario y si son diferentes hace una peticion al metodo put, ahi te lo mando y lo ves!

2022-02-03 16:10 UTC, FlaviaCohen approved these changes
Solucionar conflictos

2022-02-04 17:55 UTC, merged