formulario de novedades
alkemyTech/OT127-CLIENT pull request #34
Opened 2022-01-26 04:48 UTC by silversurferbeats

Criterios de aceptación: En base a la fórmula de creación existente que contiene los campos Título, Contenido y Categoría, agregue el campo Imagen y obtenga las categorías desde el endpoint /categories. 
Además, para el Contenido, reemplaza el campo de texto por la librería CKEditor.
El objeto se convierte en un formulario reutilizable para editar acciones y crear novedades. Para esto, deberá poder comportarse de forma diferente según reciba una novedad o no. En caso de no recibir un objeto de novedad existente, mostrar los campos vacíos y realizar una petición POST en el punto final de creación de novedades (/noticias). Si desea recibir un objeto de novedad, complete la fórmula con los campos del mismo y realice una solicitud de PATCH en el punto final de la actualización del servidor (/noticias/:id). Este formulario se mostrará en el backoffice tanto en las rutas de creación y edición de una novela (/backoffice/news).

2022-01-27 03:13 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-01-27 03:13 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> -import React, { useState } from 'react';
Ojo que acá estás eliminando este formulario de Categorías y creo que es trabajo de alguno de tus compañeros.

2022-01-27 03:13 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +const CategoriesForm = () => {
Este formulario no debería ser el NewsForm? Poruqe se llama categories?

2022-01-27 03:13 UTC, FlaviaCohen commented on yarn.lock
>    "version" "7.16.8"
Este archivo no debería estar traqueado por git. Te pido porfa que dentro del archivo .gitignore escribas "yarn.lock", luego borres este archivo y en la terminal pongas yarn install

2022-01-27 15:36 UTC, silversurferbeats commented on src/Components/Categories/CategoriesForm.js
> -import React, { useState } from 'react';
actualizacion carpeta Categoria/CategoriesForm.

2022-01-27 15:39 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
> +const CategoriesForm = () => {
Cambio de nombre de la constante CategoriesForm  a NewsForm

2022-01-27 15:40 UTC, silversurferbeats commented on yarn.lock
>    "version" "7.16.8"
actualizacion de archivo .gitignore (yarn.lock)

2022-01-28 01:51 UTC, FlaviaCohen requested changes

2022-01-28 01:51 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +        /* // => OnSumit
Este comentario hay que borrarlo si no lo vas a usar

2022-01-28 01:51 UTC, FlaviaCohen commented on src/App.js
>              component={ActivitiesForm}
Hay que modificar la ruta de NewsForm ya que se va a renderizar en el backoffice. Las dos rutas en las que hay que mostrarlo son: 

`/backoffice/news` y `/backoffice/news/:id`

2022-01-28 01:51 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
>  const NewsForm = () => {
Falta validar si el formulario recibe un id (eso va a pasar cuando la url sea /backoffice/news/:id). 

Podés usar el hook `useParams` para comprobar si existe, y en caso de que si tenés que hacer una petición get de la info de novedades y setear esos valores como iniciales, luego hacés un put.

En caso de que no exista id los valores iniciales serán strings vacíos y hacés un post.

2022-01-28 01:51 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +            console.log(response);
no dejemos console.logs en los PRs

2022-01-28 01:51 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +                <label htmlFor="name">Titulo</label>
- Falta integrar CKEditor ( que si se te complica mucho lo dejamos sin eso) 

- Falta agregar un campo para la imagen

2022-01-28 01:51 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +                    <option value="option1" >categorie1</option>
Las opciones de categorías deben ser traidas de la API, del endpoint de categorias. Deben ser categorías existentes, no harcodeadas.

2022-01-31 13:51 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
> +                <label htmlFor="name">Titulo</label>
no puedo implementar CKEditor. 
Agrego el campo de la imagen.

2022-01-31 13:51 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
> +                    <option value="option1" >categorie1</option>
traigo categorias de novedades desde la API.

2022-01-31 13:52 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
> +            console.log(response);
extraccion de todos los console.logs

2022-01-31 13:52 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
> +        /* // => OnSumit
extraccion de comentarios

2022-01-31 20:50 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
>  const NewsForm = () => {
incluyo useParams para la validacion de id.

2022-02-01 00:44 UTC, FlaviaCohen requested changes

2022-02-01 00:44 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +                console.log(response);
No dejemos console.logs en los PRs. Podés poner un `return response`

2022-02-01 00:44 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +                console.log(error);
Lo mismo acá:` return error`

2022-02-01 00:44 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +        const URLNews = 'http://ongapi.alkemy.org/api/news';
Esta lógica hay que declararla afuera del useEffect y dentro solo llamarla. 

Además se tiene que ejecutar sólo si el id existe. Dentro del then tiene que setear como estado inicial los valores que traiga de la API

2022-02-01 00:44 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +                //to do
El catch puede retornar el error

2022-02-01 00:44 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +    const [newsAPI, setNewsAPI] = useState([]);
Este nombre no es muy descriptivo, si vas a traer la información de news desde la API podrías llamarla newsData. 
Por otro lado la info que vas a traer es la data de 1 novedad, o sea debería ser inicialmente un objeto con varios campos.

`const [newsData, setNewsData] = useState({name: '', description: '', image: ''})`

Podés llamarlo newsData, formData, formValues (alguno de esos tres nombres es descriptivo)

2022-02-01 00:44 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +        const name = values.name;
No entiendo muy bien como estás armando acá el objeto pero hay código demás. si estás recibiendo values podés desestructurarlo así: `const {name, description} = values` para no repetir el `values.`

const NewForm que campo sería?

2022-02-01 00:44 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +                console.log(response);
No dejemos console.logs, `return response`

2022-02-01 00:44 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +                //to do
`return error`

2022-02-01 00:44 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +        const baseUrl = 'http://ongapi.alkemy.org/api/news';
esta url la estás usando 2 veces, te conviene declararla afuera para poder acceder en ambas funciones

2022-02-01 00:44 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +        initialValues={{ name: "", description: "", NewForm: ""  }}
Así es como debería estar declarado el estado local del componente. 

`const [formValues, setFormValues] = useState({name: "", description: "", NewForm: ""})`
Luego acá le pasas al Formik `initialValues=(formValues)`

2022-02-01 00:44 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +                <label htmlFor="NewForm">New Form</label>
No se que campo es NewForm...

2022-02-01 01:29 UTC, FlaviaCohen requested changes

2022-02-01 01:29 UTC, FlaviaCohen commented on src/App.js
> +          <Route path="/create-news/:id?" component={NewsForm} />
Acá no es una ruta o la otra, van las dos. Entonces cuando el usuario ingrese a la ruta de crear va a ir a /create-news y si ingresa a la ruta de editar va a ir a /create-news/:id

2022-02-01 01:29 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +    const [newsAPI, setNewsAPI] = useState([]);
También te falta la categoría

2022-02-01 01:30 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +            console.log(response);
Sigue habiendo muchos console.logs

2022-02-01 01:30 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +                    <option value="option1" >categorie1</option>
No veo donde están las categorías traídas de la API

2022-02-01 13:26 UTC, silversurferbeats commented on src/App.js
> +          <Route path="/create-news/:id?" component={NewsForm} />
agrego las dos rutas.

2022-02-01 13:26 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
> +                <label htmlFor="NewForm">New Form</label>
cambio de campo a Categorias.

2022-02-01 13:27 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
> +        initialValues={{ name: "", description: "", NewForm: ""  }}
implemento useState para las initialValues.

2022-02-01 13:27 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
> +        const baseUrl = 'http://ongapi.alkemy.org/api/news';
coloco solo una URL al comienzo del componente. (baseUrl).

2022-02-01 13:28 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
> +                //to do
implemento return error.

2022-02-01 13:28 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
> +                console.log(response);
elimino todo los console.logs.

2022-02-01 20:24 UTC, FlaviaCohen requested changes

2022-02-01 20:24 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +        const name = setFormValues.name;
acá estás accediento a los valores de formValues, entonces `const name = formValues.name`, lo mismo con las otras constantes

2022-02-01 20:28 UTC, FlaviaCohen requested changes

2022-02-01 20:28 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +        axios.get(baseUrl)
esta lógica hay que declararla en una constante por fuera del useEffect y dentro sólo ejecutarla. 
Además hay que ejecutarla sólo si existe id

2022-02-02 14:36 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
> +        axios.get(baseUrl)
extraigo la logica fuera del useEffect, refactorizacion codigo.

2022-02-02 14:37 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
> +        const name = setFormValues.name;
refactorizacion de inicialValues.

2022-02-02 15:59 UTC, FlaviaCohen requested changes

2022-02-02 15:59 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +const SlidesForm = () => {
Gabi, reemplazaste el formulario de Novedades por el formulario de Slides!

2022-02-02 20:19 UTC, silversurferbeats commented on src/Components/News/NewsForm.js
> +const SlidesForm = () => {
correcciones hechas

2022-02-03 12:46 UTC, silversurferbeats commented
conflicto solucionado

2022-02-03 16:05 UTC, FlaviaCohen approved these changes

2022-02-03 16:06 UTC, merged