Ot127-61/Feat/Screen listado novedades
alkemyTech/OT127-CLIENT pull request #35
Opened 2022-01-26 19:36 UTC by davidz1995

Criterios de aceptacion: Al ingresar a la ruta /backoffice/news, mostrará el listado de novedades para el usuario administrador en una tabla. El mismo tendrá datos mockeados para representar los datos, que posteriormente se obtendrán desde el endpoint de listado de novedades. La tabla mostrará los campos name, image, createdAt, y las acciones para eliminar y editar una novedad. En la sección superior, mostrará un componente <Link> que redirigirá a la ruta /backoffice/news/create, permitiendo crear una novedad

2022-01-27 04:00 UTC, FlaviaCohen requested changes

2022-01-27 04:00 UTC, FlaviaCohen commented on src/Components/News/NewsList.js
> +      <TableContainer component={Paper}>
La tarjeta pide que muestres un listado, no una tabla. Debe ser un tag <ul/> y dentro sus tags <li/> correspondientes.

2022-01-27 04:00 UTC, FlaviaCohen commented on src/Components/News/NewsList.js
> +  const createData = (name, image, createdAt, actions) => {
No veo necesario este método, podés mapear directamente el mock puesto que ya es un array con toda la info que necesitás y la estás devolviendo en el mismo formato que la recibís

2022-01-27 04:00 UTC, FlaviaCohen commented on src/Components/News/NewsList.js
> +  const rows = newsMock.map((mock) =>
Tampoco veo necesario esto, podes mapear directamente el mock

2022-01-27 17:56 UTC, davidz1995 commented on src/Components/News/NewsList.js
> +      <TableContainer component={Paper}>
Hola Fla, la tarjeta si me pide que lo muestre en una tabla, dejo acá un fragmento de la tarjeta.

_**Al ingresar a la ruta /backoffice/news, mostrará el listado de novedades para el usuario administrador en una tabla.
 La tabla mostrará los campos name, image, createdAt, y las acciones para eliminar y editar una novedad.**_

2022-01-27 18:04 UTC, davidz1995 commented on src/Components/News/NewsList.js
> +  const createData = (name, image, createdAt, actions) => {
Resuelto

2022-01-27 18:05 UTC, davidz1995 commented on src/Components/News/NewsList.js
> +  const rows = newsMock.map((mock) =>
Resuelto

2022-01-28 02:34 UTC, FlaviaCohen commented on src/Components/News/NewsList.js
> +      <TableContainer component={Paper}>
Tenés razón! Ahí la leí de nuevo... mala mía! :P

2022-01-28 02:37 UTC, FlaviaCohen approved these changes

2022-01-28 02:38 UTC, FlaviaCohen requested changes
Resolver conflictos

2022-01-30 15:47 UTC, FlaviaCohen approved these changes

2022-01-30 15:48 UTC, merged