OT127-71/Feat/metodo-reutilizable-peticion-put-endpoints-privados
alkemyTech/OT127-CLIENT pull request #38
Opened 2022-01-27 17:04 UTC by danieldamian09

Summary 

- Create function to make put requests to private api endpoints

2022-01-28 02:52 UTC, FlaviaCohen requested changes

2022-01-28 02:52 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +		Group: 01, //Aqui va el ID del equipo!!
El id del grupo es 127

2022-01-28 02:52 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +			//to do
tendrías que poner un `return res.data` acá

2022-01-28 02:52 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +			//to do
y acá un `return err`

2022-01-28 02:52 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +export function Put() {
Utilicemos arrow function

2022-01-28 21:46 UTC, danieldamian09 commented
Fla realizadas las correcciones, te anexo, capture de pantalla, seguro voy a tener conflictos, pero cuando hagas marge de la rama de Cris
![Captura de pantalla 2022-01-28 181205](https://user-images.githubusercontent.com/63797901/151625945-029981c3-2ffd-4298-ac63-847a2a30530c.png)

2022-01-30 16:06 UTC, FlaviaCohen reviewed
Solucionar conflictos

2022-01-30 16:06 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +			return
te falta retornar lo que te trae el put. 

la línea 25 debería ser `return res` y la línea 29 es `return err`

2022-01-31 16:39 UTC, FlaviaCohen approved these changes

2022-01-31 16:40 UTC, merged