OT127-48-comp reutilizable para mostrar títulos
alkemyTech/OT127-CLIENT pull request #4
Opened 2022-01-20 19:00 UTC by nelrodriguez22

Crear componente reutilizable para mostrar títulos

2022-01-20 23:06 UTC, FlaviaCohen requested changes

2022-01-20 23:06 UTC, FlaviaCohen commented on src/Components/Titulosynovedades/TitleNews.js
> +	const { title,news, image } = props
Para desestructurar props es más conveniente y resumido hacerlo en la línea 5 de esta manera: 

`export const TitleNews = ({title, news, image}) => {`

2022-01-20 23:06 UTC, FlaviaCohen commented on src/Components/Titulosynovedades/TitleNews.js
> +export const TitleNews = (props) => {
El componente debería llamarse "Title" ya que se reutilizará en todas las secciones de la web, no solamente en /news por ende debemos usar un nombre genérico

2022-01-20 23:06 UTC, FlaviaCohen commented on src/Components/Titulosynovedades/TitleNews.js
> +		<div className="container">
Google sobre el método BEM para nombrar clases: 

B.E.M. significa "Block Element Modifier" y la sintaxis es la siguiente: 
`       "block__element-modifier"`

En este caso el bloque sería `title`, por ende la clase del div contenedor podría ser `title__container` o simplemente `title`.

`title__body` sería otra
title-body-side no es muy descriptivo, más vale llamarlo `title__image`

2022-01-20 23:06 UTC, FlaviaCohen commented on src/Components/Titulosynovedades/TitleNews.js
> +			izquierda y el resto a la derecha las novedades  */}
Si lees la tarjeta, especifica que la imagen debe ir como background del título, así que a futuro no irá a la izquierda ocupando un 30% como decís sino como fondo.

2022-01-20 23:06 UTC, FlaviaCohen commented on src/Components/Titulosynovedades/TitleNews.js
> +					<p>{news}</p>
El título no recibirá news, solamente recibirá un texto (propio del título) y una imagen.

2022-01-20 23:08 UTC, FlaviaCohen commented
Una cosa más además de los comentarios que te dejé más arriba.

Las imagenes deben ir en la carpeta /public/assets/images

2022-01-21 00:13 UTC, nelrodriguez22 commented on src/Components/Titulosynovedades/TitleNews.js
> +	const { title,news, image } = props
una vez que hice el cambio, tengo que hacer click en "resolve conversation" o eso no es para nosotros?

2022-01-21 21:58 UTC, FlaviaCohen commented on src/Components/Titulosynovedades/TitleNews.js
> +	const { title,news, image } = props
yo la resuelvo

2022-01-21 22:58 UTC, FlaviaCohen requested changes
Mover la imagen a la carpeta /public/assets/images y eliminar la /assets de /src

2022-01-23 17:33 UTC, closed without merging

2022-01-23 17:33 UTC, FlaviaCohen commented
Falta en el nombre de la branch si es "feat o fix"