Ot127 58/feat/crear componente de contenido de actividad
alkemyTech/OT127-CLIENT pull request #44
Opened 2022-01-28 14:02 UTC by silversurferbeats

Este componente deberá renderizar el contenido obtenido como propiedad de forma dinámica. Este contenido será un texto en HTML, por lo que deberá permitir renderizar código HTML en lugar de texto plano.
Las props del componente las recibe del componente padre en 'NewsForm.js'.

2022-01-30 16:24 UTC, FlaviaCohen requested changes

2022-01-30 16:24 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +    function enviarDatos(){
Utilicemos arrow functions

2022-01-30 16:24 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +        let texto = document.getElementById('campo').value;
Lo que hace esta función no es correcto. Te pase por el chat documentación para que se entienda que es lo que pide la tarjeta. 

Por otro lado ojo porque la tarjeta 58 pide crear un componente para el contenido de actividad, y acá estas trabajando sobre el formulario de actividades. Son componentes diferentes.

2022-01-30 16:24 UTC, FlaviaCohen commented on src/Components/News/NewsForm.js
> +//Prueba
Acá se te volvieron a mezclar las branch ya que tenés trabajo de la tarjeta de novedades en la tarjeta de actividades. Ojo con esto.

2022-01-31 17:36 UTC, silversurferbeats commented on src/Components/Activities/ActivitiesForm.js
> +    function enviarDatos(){
utilizacion de arrow functions

2022-01-31 17:38 UTC, silversurferbeats commented on src/Components/Activities/ActivitiesForm.js
> +        let texto = document.getElementById('campo').value;
implemento metodo dangerouslySetInnerHTML para renderizar el contenido optenido

2022-01-31 17:41 UTC, gabi-dev-tech commented on src/Components/News/NewsForm.js
> +//Prueba
correccion de los branch. (tarjera de actividades )

2022-02-01 02:14 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-02-01 02:14 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
>          console.log(initialValues);
No dejemos console.logs en los PRs

2022-02-01 02:14 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +        campo: ''
No mezclemos idiomas. Además "campo" no es un nombre descriptivo para un campo. Tenemos que especificar que campo es, que información va a contener.

2022-02-01 02:14 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +    const formattedMessage = `
La tarjeta dice que el mensaje va a ser obtenido de forma dinámica, es decir que será obtenido por props. No es necesario declarar una variable con contenido HTML.

2022-02-01 02:14 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +                style={{ border: '1px solid', padding: '0.5rem' }}
los estilos inline son mala práctica. Si querés darle estilo a este componente tenés que crear un archivo de estilo e importarlo.

2022-02-01 16:07 UTC, silversurferbeats commented on src/Components/Activities/ActivitiesForm.js
> +                style={{ border: '1px solid', padding: '0.5rem' }}
agrego los estilos en un archivo aparte.

2022-02-01 16:09 UTC, silversurferbeats commented on src/Components/Activities/ActivitiesForm.js
> +        campo: ''
correccion de idiomas.

2022-02-01 16:09 UTC, silversurferbeats commented on src/Components/Activities/ActivitiesForm.js
>          console.log(initialValues);
elimino console.logs.

2022-02-01 19:41 UTC, silversurferbeats commented on src/Components/Activities/ActivitiesForm.js
> +    const formattedMessage = `
implemente el mensaje a travez de props, pero si saco "formattedMessage" figura error.

2022-02-01 21:00 UTC, FlaviaCohen approved these changes, later dismissed

2022-02-01 21:00 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +    const formattedMessage = `
Es que no le está llegando por props.

2022-02-01 21:00 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +    const formattedMessage = `
Además no es en este componente en el que tenés que mostrar ese texto, es en el componente "contenido de actividad", este es "formulario de actividad". Ojo con mezclar componentes.

2022-02-02 15:02 UTC, silversurferbeats commented
realizo un nuevo archivo (Activities.js) donde se encuentra el componente.
![image](https://user-images.githubusercontent.com/67937686/152179447-b0a5fe6f-cc74-4ecc-81e0-d8e6a90ba67e.png)

2022-02-03 02:06 UTC, FlaviaCohen requested changes

2022-02-03 02:06 UTC, FlaviaCohen commented on src/Components/Activities/Activities.js
> +const Activities = ({mensage}) => {
Este componente llamemoslo "Activity" ya que va a tener el contenido de una actividad, debería estar en singular el nombre. Es lo único que falta además de solucionar conflictos y estaría lista.

2022-02-04 16:30 UTC, silversurferbeats commented on src/Components/Activities/Activities.js
> +const Activities = ({mensage}) => {
paso los cambios hecho en el nombre del componente 'Activity' , tambien soluciono conflictos.

2022-02-04 18:01 UTC, FlaviaCohen requested changes

2022-02-04 18:01 UTC, FlaviaCohen commented on src/Components/Activities/Activities.js
>      return(
No gabi me entendiste mal la corrección. El componente debe llamarse Activity. O sea, tenés que cambiar "Activities" por "Activity", message dejalo como estaba.

2022-02-04 18:01 UTC, FlaviaCohen commented on src/Components/Activities/Activities.js
> +const Activities = ({mensage}) => {
Me entendiste mal Gabi, message dejalo como está. "Activities" cambialo por "Activity"

2022-02-04 20:09 UTC, silversurferbeats commented on src/Components/Activities/Activities.js
> +const Activities = ({mensage}) => {
ok, ya estan listo los cambios.

2022-02-05 00:52 UTC, FlaviaCohen approved these changes

2022-02-05 00:52 UTC, merged