OT127-72/feat/patch-request-to-private-API-endpoints
alkemyTech/OT127-CLIENT pull request #47
Opened 2022-01-28 15:00 UTC by cardosonicolas

Crear método reutilizable que realice una petición PATCH a los endpoints privados de la API:
Criterios de aceptacion: El método deberá recibir una ruta destino, un identificador y un objeto con la estructura de datos para enviar en el BODY. Deberá invocar el método para agregar el encabezado Authorization en base al token del usuario y realizar una petición PATCH. Agregarlo en privateApiService.js.

Summary

- Creacion de la funcion privateServicePatch.

Evidence:
![funcion](https://user-images.githubusercontent.com/65054792/151569521-7dcc6789-186c-48f2-9054-6bd37231b2e8.png)

![ejemplo](https://user-images.githubusercontent.com/65054792/151569540-c1ff085b-0252-4c88-a488-c2cc0c532512.png)

2022-01-30 16:10 UTC, FlaviaCohen requested changes

2022-01-30 16:10 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    axios.patch(url, data, {
recordá que el método que acepta la API es put, no patch. Voy a cambiarlo en la tarjeta, no tenías porque saberlo.

2022-01-30 16:10 UTC, FlaviaCohen commented
Solucionar conflictos

2022-01-30 21:18 UTC, cardosonicolas commented on src/Services/privateApiService.js
> +    axios.patch(url, data, {
Recuerdo que habia una tarjeta que ya pedia con put, es esta: [https://alkemy-labs.atlassian.net/browse/OT127-71](url), lo cambio igual?

2022-01-31 16:43 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    axios.patch(url, data, {
Tenés razón! y método PUT a ruta pública no va a haber porque el usuario no debería poder editar el contenido de la página. Lo dejamos en PATCH

2022-01-31 16:44 UTC, FlaviaCohen requested changes
Resolver conflictos

2022-02-01 02:23 UTC, FlaviaCohen approved these changes

2022-02-01 02:23 UTC, merged