Slider de inicio
alkemyTech/OT127-CLIENT pull request #5
Opened 2022-01-21 21:31 UTC by solismatias

### Tarea:
Se deberá crear un componente Carrusel que renderice los Slides para la pagína de "Inicio", con la finalidad de detallar información sobre la ONG
La información se mostrára de forma dinámica obtenida del endpoint de slides. Inicialmente, estos datos serán obtenidos de un array de objetos con las propiedades: image, title y description.
El componente deberá contener botones a la derecha e izquierda, para realizar la acción de cambiar la información al siguiente o al anterior slide.
La información de los slides deberá cambiar automaticamente a los 5 segundos para mostrar el siguiente slide.
El componente debe ser totalmente responsive

### Evidencia:
![prueba2](https://user-images.githubusercontent.com/67497671/150602461-8f014103-e60c-461e-bbd2-a73a9bc88b41.png)
![prueba](https://user-images.githubusercontent.com/67497671/150602472-47b11f8d-6c03-4e60-b9ba-d0354429304b.png)

Aclaracion:
los endpoints de slider con el texto de la descipcion vienen con tags, esto no es error en el codigo
![api](https://user-images.githubusercontent.com/67497671/150602475-233f1167-d0f8-4c55-ac49-064232feb978.png)

2022-01-21 22:00 UTC, FlaviaCohen commented
- Solucionar conflictos de branch
- Nombrar la branch como acordamos: OT127-id/Feat o Fix/Breve descripción

2022-01-21 22:08 UTC, FlaviaCohen requested changes

2022-01-21 22:08 UTC, FlaviaCohen commented on src/Components/Slides/SliderHome.css
> +.slider__item {
la idea de utilizar el método BEM es poder anidar estilos para no repetir tanto código. 

Tendrías que instalar node-sass, cambiar la extensión de este archivo por .scss y anidar de la siguiente manera: 

```
.slider {
    &__item{
    }
    &__img{
    }
    &__text-container{
    }
}
```

etc.

2022-01-21 22:09 UTC, FlaviaCohen commented
- Solucionar conflictos de branch
- Nombrar la branch de acuerdo a lo que conversamos y está pineado en el chat de discord

2022-01-22 17:24 UTC, solismatias commented on src/Components/Slides/SliderHome.css
> +.slider__item {
Okey, ahi lo instale y parece funcionar bien

2022-01-22 17:48 UTC, closed without merging