Ot127 64/feat/slide-list-screen-backoffice
alkemyTech/OT127-CLIENT pull request #51
Opened 2022-01-30 00:42 UTC by cardosonicolas

Al ingresar a la ruta /backoffice/slides, mostrará el listado de slides de la ONG para el usuario administrador en una tabla. El mismo tendrá datos mockeados para representar los datos, que posteriormente se obtendrán desde el endpoint de listado de slides. La tabla mostrará los campos title, image y order, y las acciones para eliminar y editar. En la sección superior, mostrará un componente <Link> que redirigirá a la ruta /backoffice/slides/create.

Summary

- Al ingresar a la ruta "/backoffice/slides" muestra una tabla con un listado de los slides.
- La tabla muestra los campos title, image, order y las acciones para editar  y eliminar.
- El boton editar redirecciona a la ruta "/backoffice/slides/edicion/:id"
- El boton eliminar redirecciona a la ruta "/backoffice/slides/delete/:id"
- En la sección superior muestra un componente Link que redirecciona a la ruta "/backoffice/slides/create".

Evidence

![evidence](https://user-images.githubusercontent.com/65054792/151682241-ae7e1fca-96c6-4893-ad59-d84365a9b3a6.png)

Create
![create](https://user-images.githubusercontent.com/65054792/151682422-0f1eddf1-2b3e-447c-bfa5-cbda3ba9ac85.png)
Edit
![edit](https://user-images.githubusercontent.com/65054792/151682428-9c003cf6-e4b7-495c-9f90-30e6c472ddfe.png)
Delete
![delete](https://user-images.githubusercontent.com/65054792/151682430-af4723dd-9739-47e9-ae31-d1fe91213791.png)

2022-01-30 15:49 UTC, FlaviaCohen commented
Muy bien documentado este PR!!! 👏🏼👏🏼👏🏼

2022-01-30 15:53 UTC, FlaviaCohen requested changes

2022-01-30 15:53 UTC, FlaviaCohen commented on src/Pages/Slides/SlideList.js
> +const getSlidesData = new Promise((resolved) => resolved(slides));
El nombre `res` hace alución a `response`, si no querés abreviarlo y para que sea descriptivo pongamosle `response` y no `resolved`

2022-01-30 15:53 UTC, FlaviaCohen commented on src/Pages/Slides/SlideList.js
> +const getSlidesData = new Promise((resolved) => resolved(slides));
Otra cosa... si este va a ser un método que vas a utilizar en el componente es convención declararlo dentro de ese componente. De hecho podés incluirle la segunda parte de la lógica que setea el estado local. No hay necesidad de hacerlo por separado. 

Como comentario final le pondría un .catch para que en caso de que falle la petición puedas mostrar algo. Por el momento podemos dejarlo como //TODO

2022-01-30 15:53 UTC, FlaviaCohen commented on src/Pages/Slides/SlideList.js
> +    <div style={{ width: "90%", padding: "1em", margin: "0 auto" }}>
Los estilos inline son mala práctica. Necesitamos una hoja de estilo importada en el este componente y declarar esto ahí.

2022-01-30 15:54 UTC, FlaviaCohen commented
Solucionar conflictos

2022-01-31 19:05 UTC, cardosonicolas commented on src/Pages/Slides/SlideList.js
> +const getSlidesData = new Promise((resolved) => resolved(slides));
> Otra cosa... si este va a ser un método que vas a utilizar en el componente es convención declararlo dentro de ese componente. De hecho podés incluirle la segunda parte de la lógica que setea el estado local. No hay necesidad de hacerlo por separado.
> 
> Como comentario final le pondría un .catch para que en caso de que falle la petición puedas mostrar algo. Por el momento podemos dejarlo como //TODO

La idea era hacer una funcion que simule una peticion GET con la misma firma que Mati va a hacer en su ticket. 
De todas formas, no estoy entendiendo bien este comentario.

2022-02-01 02:20 UTC, FlaviaCohen requested changes

2022-02-01 02:20 UTC, FlaviaCohen commented on src/Pages/Slides/SlideList.js
> +const getSlidesData = new Promise((res) => res(slides));
1. Este método declaralo adentro de SlidesList. 
2. Este método no está haciendo ningún llamado. La tarjeta no lo pide por ende no es una buena práctica declararlo a medias.

2022-02-01 02:20 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +}z
Ojo que acá quedó un typo

2022-02-01 02:21 UTC, FlaviaCohen commented on src/Pages/Slides/SlideList.js
> +const getSlidesData = new Promise((resolved) => resolved(slides));
Ahí te lo aclaré en un comentario más abajo.

2022-02-01 21:05 UTC, FlaviaCohen approved these changes

2022-02-01 21:05 UTC, merged