OT127-31/Feat/form-edic-creac-testimonios
alkemyTech/OT127-CLIENT pull request #54
Opened 2022-01-31 03:49 UTC by nelrodriguez22

- atom1-agregado-campo-imagen
- ckeditor agregado
- atom2
- atom-changes
- atom-func-editupd
- atom1-fn-edupd
- atom-formik
- atom-agregado-campos
- upd-formik
- cketerminado

2022-01-31 16:24 UTC, FlaviaCohen requested changes

2022-01-31 16:24 UTC, FlaviaCohen commented on src/Components/Testimonials/TestimonialsForm.js
> +	const [ name, setName ] = useState("")
Podés tratar al formulario como si fuera una entidad, en ese caso se declara un solo estado así: 

`const [formValues, setFormValues] = useState({ name: '', description: '', image: ''}) `

y se actualiza con un 

`const handleChange = (e, property) => { setFormValues({...formValues, [property]: e.target.value})} `

De esta forma el código queda más limpio. Justo en este formulario tenés solo 3 estados locales, 3 inputs para controlar pero hay formularios que pueden llegar a tener 20 campos y declarar 20 estados ya queda feo. Por eso se separan los estados por entidades.

2022-01-31 16:24 UTC, FlaviaCohen commented on src/Components/Testimonials/TestimonialsForm.js
> +	const image = (e) => {
Fijate si vas a implementar el cambio que te sugerí anteriormente y unificar los handlers. Sino este método debería llamarse handleImage para que sea descriptivo.

2022-01-31 16:24 UTC, FlaviaCohen commented on src/Components/Testimonials/TestimonialsForm.js
> +		const url = id ? `${baseUrl}/${id}` : `${baseUrl}`
Este condicional no debería estar ya que la función GET se va a ejecutar solamente si existe id. Si no existe id no entrará en el if por lo tanto no se ejecuta nada.

2022-01-31 16:24 UTC, FlaviaCohen commented on src/Components/Testimonials/TestimonialsForm.js
> +		initialValues: {
si hacés la corrección de los estados acá sólo le pasas `formValues`

2022-01-31 16:24 UTC, FlaviaCohen commented on src/Components/Testimonials/TestimonialsForm.js
> +		validate: (values) => {
Estoy tiene que estar declarado en una constante por fuera del JSX, el JSX debe permanecer lo más limpio posible.

2022-01-31 16:24 UTC, FlaviaCohen commented on src/Components/Testimonials/TestimonialsForm.js
> +		onSubmit: (values) => {
Lo mismo con esto, debe existir la función handleSubmit por fuera del JSX y acá solo se la pasas

2022-01-31 16:24 UTC, FlaviaCohen commented on src/Pages/Home.js
>          <SliderHome />
Esto no corresponde a esta tarea.

2022-02-09 22:55 UTC, nelrodriguez22 commented on src/Components/Testimonials/TestimonialsForm.js
> +	const [ name, setName ] = useState("")
fla recorda que no pude hacer funcionar el cke tomando los 3 estados como una entidad por eso los maneje por separado.

2022-02-10 02:41 UTC, FlaviaCohen requested changes

2022-02-10 02:41 UTC, FlaviaCohen commented on src/Components/Testimonials/TestimonialForm.js
> +		const bUrl = `${url}/${id}`
que significa esta variable `bUrl`? No es un nombre descriptivo. Podés directamente pasarle al axios esto en el primer parámetro: `${url}/${id}`. No tiene sentido declarar una misma variable dos veces adentro de dos métodos diferentes... o la declarás afuera y la usás dos veces, o declarás directamente la url como la tenés y le pasas la concatenación de la url + id.

2022-02-10 02:41 UTC, FlaviaCohen commented on src/Components/Testimonials/styles.scss
> +}
Esto está raro indentado, estás usando prettier?

2022-02-10 02:41 UTC, FlaviaCohen commented on src/Pages/Home.js
>          <SliderHome />
SliderHome no corresponde a esta tarea, que hacemos con este cambio?

2022-02-10 21:31 UTC, nelrodriguez22 commented on src/Components/Testimonials/TestimonialForm.js
> +		const bUrl = `${url}/${id}`
si asi ${url}/${id} era como lo tenia antes, pero ya estaba re quemado a esa altura del dia y no tengo idea que quise hacer

2022-02-10 21:32 UTC, nelrodriguez22 commented on src/Components/Testimonials/styles.scss
> +}
al parecer ahora esta funcionando normal, desinstale la extension, volvi la config a 0 y sincronice de nuevo.

2022-02-10 21:35 UTC, nelrodriguez22 commented on src/Pages/Home.js
>          <SliderHome />
Ahora con respecto a esto si que no tengo idea que hace ahi, ya la primera vez fijate que mi commit es de "fixconflicts" no es que lo modifique por alguna tarjeta o razón sino porque me salia en los conflictos y lo mismo con este ultimo. Asi que no se q hacer con ese archivo del demonio

2022-02-12 19:48 UTC, solismatias commented on src/Pages/Home.js
>          <SliderHome />
hola @FlaviaCohen hola @nelrodriguez22, estaba chusmeando el pr jeje 👀, @FlaviaCohen el componente SliderHome ya estaba en este archivo de Home.js, lo puse yo en el primer sprint, es el Carrusel del inicio, capaz el Prettier de Nelson corrigio algo y quedo como que el fue el que lo agregó, pero en verdad ya estaba

2022-02-15 02:12 UTC, FlaviaCohen requested changes

2022-02-15 02:12 UTC, FlaviaCohen commented on src/Components/Testimonials/TestimonialForm.js
> +		const bUrl = `${url}/${id}`
Bueno... o le ponemos un nombre descriptivo a la variable o dejás directamente la concatenación. Si vas a declarar una variable delcarala afuera de los métodos get y put y así no tenés que declararla dos veces.

2022-02-15 02:43 UTC, nelrodriguez22 commented on src/Components/Testimonials/TestimonialForm.js
> +		const bUrl = `${url}/${id}`
@FlaviaCohen que raro que sigas viendo esa version porque los cambios lo hice hace 4 dias, asi esta mi archivo actualmente https://github.com/alkemyTech/OT127-CLIENT/blob/OT127-31/Feat/form-edic-creac-testimonios/src/Components/Testimonials/TestimonialForm.js ...y hace un rato hasta corregi conflictos y todo

2022-02-16 16:09 UTC, FlaviaCohen approved these changes

2022-02-16 16:09 UTC, merged