Ot127 80/feat/extend-http-service-for-contacts-request
alkemyTech/OT127-CLIENT pull request #57
Opened 2022-01-31 19:55 UTC by cardosonicolas

Crear un servicio con todos los metodos necesarios para las diferentes peticiones de los componentes de Contactos a la API, utilizando el servicio HTTP base.
Conectar los componentes de Contacto con el servicio creado.

Summary

- Creacion de la funcion postContact para hacer una peticion POST.
- Importada la funcion postContact en el componente ContactForm.

Evidence
![contactServices](https://user-images.githubusercontent.com/65054792/151863163-096e92ed-7a35-432d-b050-41aa6b57f37c.png)

2022-02-01 02:40 UTC, FlaviaCohen requested changes

2022-02-01 02:40 UTC, FlaviaCohen commented on yarn.lock
>      "strip-json-comments" "^3.1.1"
agregá el yarn.lock al .gitignore si es que no lo tenés así git deja de trackear este archivo.

2022-02-01 02:49 UTC, cardosonicolas commented on yarn.lock
>      "strip-json-comments" "^3.1.1"
Si si, esta en .gitignore desde la primera vez que me lo pediste

![Screenshot from 2022-01-31 23-48-18](https://user-images.githubusercontent.com/65054792/151906174-4922852d-8d9d-42ac-ae16-20f5e691ed15.png)

Esta bien asi?

2022-02-01 21:11 UTC, FlaviaCohen commented on yarn.lock
>      "strip-json-comments" "^3.1.1"
Si perfecto!

2022-02-01 21:11 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-02-02 02:52 UTC, FlaviaCohen approved these changes

2022-02-02 02:52 UTC, merged