creacion formulario miembro
alkemyTech/OT127-CLIENT pull request #59
Opened 2022-01-31 22:47 UTC by silversurferbeats

Realizo  formulario para editar los campos nombre, imagen, descripción y enlaces de redes sociales. No pude implementar CKEditor. Todos los campamentos son obligatorios, y deben validarse al hacer presentar. Se debe mostrar los datos por consola en casos que sean correctos, ya que posteriormente se realizará una petición a la API.

2022-02-03 15:36 UTC, FlaviaCohen requested changes

2022-02-03 15:36 UTC, FlaviaCohen commented on src/Components/Members/Members.scss
> +    button {
Ojo con este button que sigue siendo un selector universal. Si le das estilo así va a afectar a todos los botones de la web. Dale un nombre de una clase

2022-02-03 15:36 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +const NewsForm = () => {
Está perfecto todo, falta la lógica de comprobación de id. Si recibe id tiene que hacer un get y completar el formulario y en el submit un put, sino el formulario se inicia vacío y en el submit hace un post. Igual que lo hiciste en el otro formulario (creo que era la tarjeta 28).

2022-02-04 16:14 UTC, silversurferbeats commented on src/Components/Members/MembersForm.js
> +const NewsForm = () => {
hola fla, dejo los cambios hecho de la logica de comprobacion de id .

2022-02-04 17:59 UTC, FlaviaCohen requested changes

2022-02-04 17:59 UTC, FlaviaCohen commented on src/Components/Members/Members.scss
> +* {
Este es un selector universal. Va a afectar a todos los elementos de la página, si lo vas a usar debería estar en una hoja de estilo global, no acá en el estilo de Members

2022-02-04 17:59 UTC, FlaviaCohen commented on src/Components/Members/Members.scss
> +    button {
Esto no está resuelto

2022-02-04 17:59 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +        setLoading(true);
Acá hay dos lógicas... getDataById debería tener sólo la lógica de la línea 30 a la 35 y ejecutarse en el useEffect, el resto es la lógica del handleSubmit que no se porque no lo tenés declarado pero lo estás usando en el JSX. Porfa separá estas lógicas.

2022-02-04 23:09 UTC, silversurferbeats commented on src/Components/Members/MembersForm.js
> +        setLoading(true);
Asi es, el handleSubmit estaba de mas, de las pruebas anteriores. Corrijo la logica la logica  y tambien solucion de conflictos.

2022-02-05 00:49 UTC, FlaviaCohen requested changes

2022-02-05 00:49 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +        setLoading(true);
No, el handleSubmit no estaba demás, el botón submit tiene que ejecutar una función handleSubmit pero no está declarada. Está toda la lógica junta dentro del getDataById.

2022-02-05 00:50 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +const NewsForm = () => {
Sigue estando la lógica del handleSubmit y getDataById toda junta y necesito que la separes.

2022-02-07 21:44 UTC, silversurferbeats commented on src/Components/Members/MembersForm.js
> +        setLoading(true);
Agrego handleSumit con la logica correspondiente:
![image](https://user-images.githubusercontent.com/67937686/152876526-2699cc51-0126-4539-a392-de45af70d8ce.png) 
y getDataById con logica correspondiente:
![image](https://user-images.githubusercontent.com/67937686/152876748-f5e2470f-c98f-499f-a50a-bc56a8aeb93b.png) 
donde vuelve a llamarse en useEffect.

2022-02-08 13:54 UTC, FlaviaCohen requested changes

2022-02-08 13:54 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +const NewsForm = () => {
Gabi, no está mal que copiemos y peguemos código pero fijate que estás reemplazando el componente entero de NewsForm adentro de MembersForm. Por lo menos dejale el nombre que va, sino vamos a tener el formulario de News repetido.

2022-02-08 13:54 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +        const name = setFormValues.name;
Esto ya lo hablamos, setFormValues es la función que actualiza el estado local, lo que vos querés enviarle es formValues, no setFormValues.

2022-02-08 13:54 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +    const handleChange = (e) => {
Este handleChange está incompleto porque te falta actualizar los estados de facebook, linkedIn e image. 

Y además no hace falta que hagas un if para cada input, podés hacerlo así: 

```
const handleChange = (e, property) => {
    setFormValues( { ...formValues, [property]: e.target.value} )
}
```

2022-02-08 13:54 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +        getDataById();
Esto se tiene que ejecutar sólo si el id existe

2022-02-08 13:54 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +                                onChange={(event, editor) => {
Tenés declarado un handleChange y no lo estás usando. Para que lo declaramos?

2022-02-08 13:54 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +                            onChange={(e) => {
Lo mismo acá

2022-02-08 13:54 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +                        <Field name="facebookUrl" type="facebookUrl" className='input-container' />
Esto no debería ser un Field? Porque en algunos lugares del formulario usamos `<input/>` y en otros `<Field/>`?

2022-02-08 21:58 UTC, silversurferbeats commented on src/Components/Members/MembersForm.js
> +const NewsForm = () => {
corregido a MemberForm.

2022-02-08 22:00 UTC, silversurferbeats commented on src/Components/Members/MembersForm.js
> +        const name = setFormValues.name;
corregido a formValues.

2022-02-08 22:01 UTC, silversurferbeats commented on src/Components/Members/MembersForm.js
> +    const handleChange = (e) => {
fla el handleChange  lo utilizo solo para cargar la imagen .

2022-02-08 22:02 UTC, silversurferbeats commented on src/Components/Members/MembersForm.js
> +        getDataById();
corregido con validacion de id.

2022-02-08 22:06 UTC, silversurferbeats commented on src/Components/Members/MembersForm.js
> +                                onChange={(event, editor) => {
handleChange solo lo utilizo para CKEditor, y cargar la  imagen de formik.

2022-02-08 22:06 UTC, silversurferbeats commented on src/Components/Members/MembersForm.js
> +                            onChange={(e) => {
corregido handleChange para carga de la imagen.

2022-02-08 22:07 UTC, silversurferbeats commented on src/Components/Members/MembersForm.js
> +                        <Field name="facebookUrl" type="facebookUrl" className='input-container' />
solo use <input/> en la carga de la imagen por que si lo hago con <Field/> en formik salta error.
![image](https://user-images.githubusercontent.com/67937686/153083772-4bb2f1e9-cfa6-4e11-b933-2fa1909a28b6.png)

2022-02-08 22:18 UTC, silversurferbeats commented
conflictos solucionados.

2022-02-08 23:04 UTC, FlaviaCohen requested changes

2022-02-08 23:04 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +        const name = setFormValues.name;
Sigue diciendo "setFormValues" en vez de formValues

2022-02-08 23:04 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +                                onChange={(event, editor) => {
Pasa que el nombre handleChange es por convención un método que se utiliza para manejar cambios en un input. En todo caso le pondría un nombre distinto al handler para CKEditor (handleImage por ejemplo) y este setFieldValue lo reemplazaría por handleChange. 

siempre que se ve un handleChange se sobre entiende que es el que maneja el cambio de un input.

2022-02-08 23:07 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +    const handleChange = (e) => {
Te contesté en el comentario de más abajo que tiene que ver con el mismo punto.

2022-02-08 23:10 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +                        <Field name="facebookUrl" type="facebookUrl" className='input-container' />
Es un warning, los warnings están para avisarnos que estamos haciendo algo que no está del todo bien. 
Te está diciendo que el input o Field del formulari ono está controlado y debería estarlo. Es decir que tiene que partir de una propiedad value y ese value tiene que ser un estado local del componente, el handleChange de cada input cambia el estado local y así cambia el valor del input.

2022-02-09 02:44 UTC, silversurferbeats commented on src/Components/Members/MembersForm.js
> +                                onChange={(event, editor) => {
Gracias por la sujerencia Fla! Correccion cambio de nombre a handleImage . Una pregunta Fla , El "setFieldValue " no corresponde a Formik? hace como un handle de la imagen y CKEditor.

2022-02-09 02:52 UTC, silversurferbeats commented on src/Components/Members/MembersForm.js
> +                        <Field name="facebookUrl" type="facebookUrl" className='input-container' />
Fla no he podido solucionar el error del input, lo deje asi por que he visto otros ejemplos de esta manera. Tengo entendido que en las entradas de tipo "file" no se puede definir un valor inicial que no sea "" (cadena vacía) . Escucho sugerencia .

2022-02-09 19:33 UTC, silversurferbeats commented
Fla encontre el error de la peticion put. Cambie la ruta a "/member/:id" por que no estaba recibiendo data en useParams. Finalmente todo esta andando perfecto. Tambien solucione conflictos.

2022-02-09 22:13 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +                                onChange={(event, editor) => {
La verdad no lo se porque nunca usé Formik, pero podés fijarte en los formularios que hicieron tus compañeros, todos trabajaron con formik

2022-02-09 22:17 UTC, FlaviaCohen requested changes

2022-02-09 22:17 UTC, FlaviaCohen commented on src/Components/Members/Members.scss
> +.container {
tendríamos que ponerle `.member__container` a esta clase ya que container solo es una palabra común y suele ser reservada o genérica. De esta manera evitamos colisiones con otros estilos.

2022-02-09 22:17 UTC, FlaviaCohen commented on src/Components/Members/Members.scss
> +.form {
Lo mismo para esto. Si va a ser un estilo único para el formulario de miembros debe llamarse `.member__form`, si este estilo es el estilo de todos los formularios debe ir en un archivo general de estilo o mixin.

2022-02-09 22:17 UTC, FlaviaCohen commented on src/Components/Members/Members.scss
> +        .inputs {
Mismo comentario

2022-02-09 22:17 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +        const name = setFormValues.name;
No está resuelto

2022-02-09 23:12 UTC, silversurferbeats commented
Cambio a "formValues". En mi local lo tenia asi, volvi a hacer hacer push para efectuar los cambios. 
Aprobecho para dejar doc del funcionamiento del formulario en los cambios de peticiones:
 
![image](https://user-images.githubusercontent.com/67937686/153305498-0fb77f78-e9d2-44fb-98d2-25c1408185e3.png)

![image](https://user-images.githubusercontent.com/67937686/153305803-e8369b85-2fab-4dcf-b6d0-7acbcfbd7089.png)

Por ultimo hice solucion de conflictos.

2022-02-09 23:12 UTC, silversurferbeats commented on src/Components/Members/Members.scss
> +        .inputs {
corregido.

2022-02-09 23:12 UTC, silversurferbeats commented on src/Components/Members/Members.scss
> +.form {
tambien, corregido.

2022-02-09 23:12 UTC, gabi-dev-tech commented on src/Components/Members/Members.scss
> +.container {
Ha!! si , son palabras reservadas , se me paso..  te dejo los ultimos cambios.

2022-02-10 02:53 UTC, FlaviaCohen requested changes

2022-02-10 02:53 UTC, FlaviaCohen commented on src/Components/Members/Members.scss
> +.member__form {
anidá las clases dentro de `.member` así no tenés que repetir código: 

```
.member{
    &__container{ }
    &__form { }
    &__input { }
}
```

2022-02-10 02:53 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +        const name = setFormValues.name;
Gabi, tercer comentario que te dejo sobre esto. Tenés resolver estas variables que estás declarando. setFormValues.name no existe. En todo caso sería:

`const name = formValues.name`

y así con todas las variables que están ahí

De todas formas no las estás usando así que por favor borrá de la línea 23 a la 27

2022-02-10 02:59 UTC, FlaviaCohen requested changes

2022-02-10 02:59 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +                    handleSubmit(formValues);
formValues es tu estado local, no hace falta que se lo pases como parámetro a la función, la función ya tiene acceso a formValues por estar dentro del componente.

2022-02-10 19:02 UTC, silversurferbeats commented on src/Components/Members/Members.scss
> +.member__form {
corregidos los estilos SASS

2022-02-10 19:02 UTC, gabi-dev-tech commented on src/Components/Members/MembersForm.js
> +                    handleSubmit(formValues);
cambios corregidos.

2022-02-12 00:29 UTC, FlaviaCohen requested changes

2022-02-12 00:29 UTC, FlaviaCohen commented on src/Components/Members/MembersForm.js
> +        console.log(name);
Borrá el console.log y solucioná conflictos

2022-02-12 14:45 UTC, silversurferbeats commented
Correcciones y conflictos solucionados.

2022-02-12 22:00 UTC, FlaviaCohen approved these changes

2022-02-12 22:01 UTC, merged