Ot127 41/feat/Estilos formularios
alkemyTech/OT127-CLIENT pull request #65
Opened 2022-02-01 20:29 UTC by davidz1995

Aplicados estilos a todos los formularios que estaban hechos hasta ahora, solamente faltó aplicar estilos a newsLetter porque va en footer y aun no existe.

2022-02-01 20:50 UTC, FlaviaCohen requested changes

2022-02-01 20:50 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +        className="body__form--input"
si estás utilizando el método BEM el bloque en este caso sería form y el elemento es input, entonces la clase debería ser `.form__input`

2022-02-01 20:50 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +      <button className="body__form--submit" type="submit">
esto sería `.form__button-submit` o simplemente `.form__button`

2022-02-01 20:50 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +        className="body__form--input"
Lo mismo acá: `.form__input`

2022-02-01 20:50 UTC, FlaviaCohen commented on src/Components/Auth/LoginForm.js
> +    <div className="body">
esto es un `form__container` o `form__wrapper` o simplemente `container` o `wrapper`. El nombre body no es descriptivo.

2022-02-01 20:50 UTC, FlaviaCohen commented on src/Components/Auth/LoginForm.js
> +        <Form className="body__form">
Esto sería `form`

2022-02-01 20:50 UTC, FlaviaCohen commented on src/Components/Auth/LoginForm.js
> +          <label htmlFor="email" className="body__form--label">Email</label>
`.form__label`

2022-02-01 20:50 UTC, FlaviaCohen commented on src/Components/Auth/LoginForm.js
> +          <Field name="email" type="email" className="body__form--input"/>
`form__input`

2022-02-01 20:50 UTC, FlaviaCohen commented on src/Components/Auth/LoginForm.js
> +          <ErrorMessage name="email" render={(msg) => <div className="body__form--error">{msg}</div>}/>
`.form__message-errror`

2022-02-01 20:50 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
> +    <div className="body">
Misma corrección

2022-02-01 20:50 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
> +        <Form className="body__form">
Misma corrección para todo el archivo.

2022-02-01 20:50 UTC, FlaviaCohen commented on src/Components/Categories/CategoriesForm.js
> +    <div className="body">
Misma corrección para todo el archivo

2022-02-01 20:50 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +            <Form className="body__form">
Misma corrección para todo el archivo

2022-02-01 20:50 UTC, FlaviaCohen commented on src/sass/components/_form.scss
> +.body{
la idea de usar método BEM con SASS es anidar estilos y así ahorrar código. 

Esto debería quedarte algo así: 

```
.form{
    &__input{ }
    &__label{ }
    &__button{ }
}
```

2022-02-13 03:22 UTC, davidz1995 commented on src/Components/Activities/ActivitiesForm.js
> +        className="body__form--input"
Solucionado

2022-02-13 03:22 UTC, davidz1995 commented on src/Components/Activities/ActivitiesForm.js
> +      <button className="body__form--submit" type="submit">
Solucionado

2022-02-13 03:22 UTC, davidz1995 commented on src/Components/Activities/ActivitiesForm.js
> +        className="body__form--input"
Solucionado

2022-02-13 03:22 UTC, davidz1995 commented on src/Components/Auth/LoginForm.js
> +    <div className="body">
Solucionado

2022-02-13 03:22 UTC, davidz1995 commented on src/Components/Auth/LoginForm.js
> +        <Form className="body__form">
Solucionado

2022-02-13 03:22 UTC, davidz1995 commented on src/Components/Auth/RegisterForm.js
> +    <div className="body">
Solucionado

2022-02-13 03:22 UTC, davidz1995 commented on src/Components/Auth/RegisterForm.js
> +        <Form className="body__form">
Solucionado

2022-02-13 03:22 UTC, davidz1995 commented on src/Components/Categories/CategoriesForm.js
> +    <div className="body">
Solucionado

2022-02-13 03:22 UTC, davidz1995 commented on src/Components/Contact/ContactForm.js
> +            <Form className="body__form">
Solucionado

2022-02-13 03:22 UTC, davidz1995 commented on src/sass/components/_form.scss
> +.body{
Solucionado

2022-02-13 15:26 UTC, FlaviaCohen requested changes

2022-02-13 15:26 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Acá hay un conflicto sin resolver

2022-02-13 15:26 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Acá hay otro

2022-02-13 15:26 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Acá hay otro

2022-02-13 15:26 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Acá hay otro

2022-02-13 15:26 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Acá hay otro

2022-02-13 15:26 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Acá hay otro

2022-02-13 15:26 UTC, FlaviaCohen commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Acá hay otro

2022-02-13 15:50 UTC, davidz1995 commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Resuelto

2022-02-13 15:50 UTC, davidz1995 commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Resuelto

2022-02-13 15:50 UTC, davidz1995 commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Resuelto

2022-02-13 15:50 UTC, davidz1995 commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Resuelto

2022-02-13 15:50 UTC, davidz1995 commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Resuelto

2022-02-13 15:50 UTC, davidz1995 commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Resuelto

2022-02-13 15:50 UTC, davidz1995 commented on src/Components/Contact/ContactForm.js
> +<<<<<<< HEAD
Resuelto

2022-02-13 18:16 UTC, FlaviaCohen approved these changes

2022-02-13 18:19 UTC, FlaviaCohen requested changes

2022-02-13 18:19 UTC, FlaviaCohen commented on src/Components/Auth/LoginForm.js
> +          <ErrorMessage name="email" render={(msg) => <div className="body__form--error">{msg}</div>}/>
el error message no es un modificador, es un elemento. Si el block es body entonces lo llamaría `.body__error-message` con un solo guión, y en ese caso el elemento sería error-message. Si vos le ponés doble guión medio estás diciendo que el error es un modificador. 

Podría ser un modificador en caso de que tuvieras un elemento message y tuvieras las variantes `.body__message--error` y `.body__message--success`, se entiende?

2022-02-13 18:52 UTC, davidz1995 commented
Hola Fla, la última corrección es de una versión anterior, no se porque aparecieron esos classNames, porque los había cambiado con las últimas correcciones también en ese componente. en todo caso lo volví a pushear y ojalá esta vez si aparezca bien.

2022-02-13 18:56 UTC, FlaviaCohen approved these changes

2022-02-13 18:57 UTC, merged