Ot127 106/feat/redux store and auth reducer
alkemyTech/OT127-CLIENT pull request #66
Opened 2022-02-02 18:08 UTC by Chriscaracach

- Created store/provider and configured (modified store from template)

![imagen](https://user-images.githubusercontent.com/69370931/152212004-3a5bf23e-8161-45ac-bbeb-64e7120f65c6.png)

- Created authReducer and combined in allReducers.js.

![imagen](https://user-images.githubusercontent.com/69370931/152212095-a824766d-74c7-4d55-b78e-11897dca9e38.png)

- Created authActions.js 

![imagen](https://user-images.githubusercontent.com/69370931/152212141-a046976f-4069-45ef-be05-7dd9f873eddb.png)

- Comment with object schema for actions (for future uses of actions)

![imagen](https://user-images.githubusercontent.com/69370931/152212238-96d8d7cb-da4b-4577-8141-fdb84c866c44.png)

2022-02-03 17:28 UTC, FlaviaCohen requested changes

2022-02-03 17:28 UTC, FlaviaCohen commented on src/Redux/reducers/authReducer.js
> +      return {
la idea de un reducer es que respete las condiciones que ya están declaradas en el estado inicial y modifique sólo las que la acción envía. Sobretodo porque luego tus compañeros también van a agregar otros estados iniciales al reducer que no necesariamente sean los de Auth. Por ende siempre debemos retornar el estado anterior + los nuevos estados así: 

`return { ...state, userIsLogged: true, userData: action.payload}`

si action.payload es un objeto con todas esas propiedades podés reemplazar el objeto entero directamente. 

Misma corrección para el resto de los `case`

2022-02-03 17:28 UTC, FlaviaCohen commented on src/Redux/reducers/authReducer.js
> +  switch (action.type) {
La sintaxis switch case está deprecada, quizás quieras investigar la sintaxis de objeto ya que tenés tiempo. La lógica es la siguiente: 

```
const helper: { 
                            LOGIN_USER: {...state, action.payload}, 
                            REGISTER_USER: {...state, action.payload}
                        }

return helper[action.type] || state
```

2022-02-03 19:30 UTC, Chriscaracach commented on src/Redux/reducers/authReducer.js
> +      return {
Tenés razón. Lo había puesto y lo saqué, no se porqué

2022-02-03 20:09 UTC, Chriscaracach commented on src/Redux/reducers/authReducer.js
> +  switch (action.type) {
Éste helper estaría bueno que esté en un archivo aparte no?? tipo reduxHelper.js

2022-02-04 17:22 UTC, FlaviaCohen approved these changes

2022-02-04 17:23 UTC, merged