Ot127 92/feat/spinner
alkemyTech/OT127-CLIENT pull request #67
Opened 2022-02-02 18:21 UTC by Chriscaracach

- Installed and imported library react-loader-spinner

![imagen](https://user-images.githubusercontent.com/69370931/152214051-b8a7126d-2316-403c-baeb-47b62a9ffc3b.png)

- Created component spinner.js

![imagen](https://user-images.githubusercontent.com/69370931/152214106-487565c7-fde6-4ca2-a8f1-03bcf7d518e6.png)

- Modified README.md

![imagen](https://user-images.githubusercontent.com/69370931/152214153-91cd85cf-f00e-488b-a9a2-b959c94edbad.png)

2022-02-03 17:09 UTC, FlaviaCohen approved these changes

2022-02-03 17:09 UTC, FlaviaCohen commented on README.md
> +- React-loader-spinner
Excelente que hayas actualizado el readme!

2022-02-03 19:27 UTC, Chriscaracach commented on README.md
> +- React-loader-spinner
Era parte de los requisitos de la tarjeta. Me resulta raro que le falte todo el resto todavía.

2022-02-04 18:13 UTC, FlaviaCohen requested changes

2022-02-04 18:13 UTC, FlaviaCohen commented on package.json
> +<<<<<<< HEAD
Ojo que te quedó un conflicto sin resolver

2022-02-07 16:08 UTC, FlaviaCohen approved these changes

2022-02-07 16:09 UTC, merged