Crear variables desde el entorno
alkemyTech/OT127-CLIENT pull request #75
Opened 2022-02-03 20:42 UTC by silversurferbeats

Almacenar los endpoints de listado, creación, edición y eliminación de novedades en el archivo .env, y modificar las referencias existentes para que apunten a las variables de entorno creadas. Asegurarse que este archivo sea excluido en los compromisos. 
Agregar los placeholders de estas variables en el archivo .env.example, que SI debe ser commiteado.

2022-02-07 23:07 UTC, silversurferbeats commented
conflictos solucionados

2022-02-12 00:36 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-02-12 15:00 UTC, silversurferbeats commented
Solucion de conflictos

2022-02-12 22:05 UTC, FlaviaCohen approved these changes

2022-02-12 22:05 UTC, merged