Ot127 39/feat/screen datos organizacion
alkemyTech/OT127-CLIENT pull request #8
Opened 2022-01-22 16:43 UTC by davidz1995

**Hola Fla, disculpá que se borraron las indicaciones que me habías dejado en este pr, se borraron cuando cambié el nombre de la ruta, me pasó lo mismo con los otros pr que tenía._De esta rama, quedaron hechas las correcciones que me habías pedido y en cuanto a la validación para renderizar los datos de la organización, si rompe si no le pongo la condición.**

COMO: Usuario administrador
QUIERO: Visualizar los datos de la ONG
PARA: Verificar que el contenido mostrado públicamente sea el correcto

Criterios de aceptacion: Al ingresar a la ruta /backoffice/organization se mostrarán los datos actuales de la organización (name, image, shortDescription), y la acción para acceder al formulario de edición (/backoffice/organization/edit)

2022-01-22 18:22 UTC, FlaviaCohen requested changes

2022-01-22 18:22 UTC, FlaviaCohen commented on src/Components/Organization/OrganizationData.js
> +            setOrganizationData(response.data)
En la línea 12 podemos setear como estado `response.data.data` y te ahorrás todos los `data` en el jsx, te queda más corto y limpio.

2022-01-22 18:23 UTC, FlaviaCohen requested changes

2022-01-22 18:23 UTC, FlaviaCohen commented on src/Components/Organization/OrganizationData.js
> +        <>
Instalá prettier para que el código quede bien indentado

2022-01-24 02:31 UTC, davidz1995 commented on src/Components/Organization/OrganizationData.js
> +            setOrganizationData(response.data)
Solucionado

2022-01-24 02:31 UTC, davidz1995 commented on src/Components/Organization/OrganizationData.js
> +        <>
Solucionado

2022-01-24 15:03 UTC, FlaviaCohen requested changes

2022-01-24 15:03 UTC, FlaviaCohen commented on src/App.js
> +            component={() => <Donacion message={"Quieres donar?"} />}
Si message recibe un string no es necesario ponerlo entre llaves.

2022-01-24 15:03 UTC, FlaviaCohen commented on src/Components/Auth/LoginForm.js
> +        onSubmit={(values) => {
Es preferible declarar una función por fuera del JSX que contenga toda esta lógica y mantener el código que está luego del return lo más limpio posible. Por convención lo llamamos `handleSubmit`

2022-01-24 15:03 UTC, FlaviaCohen commented on src/Components/Auth/LoginForm.js
> +          let loginUser = {
Si no vas a volver a utilizar en otro lado esta constante es preferible no declararla. mejor hacerlo directamente así: 

`setUserData([...userData, { email: values.email, password: values.password } ])`

2022-01-24 15:15 UTC, davidz1995 commented on src/App.js
> +            component={() => <Donacion message={"Quieres donar?"} />}
Solucionado

2022-01-24 15:19 UTC, davidz1995 commented on src/Components/Auth/LoginForm.js
> +        onSubmit={(values) => {
Solucionado

2022-01-24 15:21 UTC, davidz1995 commented on src/Components/Auth/LoginForm.js
> +          let loginUser = {
Solucionado

2022-01-24 20:49 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-01-24 20:58 UTC, FlaviaCohen approved these changes

2022-01-24 20:58 UTC, merged