Ot127 62/feat/pantalla listado de actividades backoffice
alkemyTech/OT127-CLIENT pull request #85
Opened 2022-02-05 18:01 UTC by silversurferbeats

Al ingresar a la ruta /backoffice/activities, mostrar el listado de actividades de la ONG para el usuario administrador en una tabla. El mismo tendrá datos mockeados para representar los datos, que posteriormente los obtendrá desde el endpoint de listado de categorías. La tabla muestra los campos nombre, imagen, y createdAt, y las acciones para eliminar y editar. En la sección superior habrá un componente <Link> que redirigirá a la ruta /backoffice/activities/create.

2022-02-07 16:02 UTC, FlaviaCohen requested changes

2022-02-07 16:02 UTC, FlaviaCohen commented on src/Components/Backoffice/Activities.js
> +  const categoryMock = [
esto debe ser ActivitiesMock. Estaba mal en la tarjeta, el endpoint debe ser el de actividades.

2022-02-07 23:40 UTC, silversurferbeats commented on src/Components/Backoffice/Activities.js
> +  const categoryMock = [
cambiado a ActivitiesMock:
![image](https://user-images.githubusercontent.com/67937686/152890215-8341dcd2-3de4-4f7d-ab2a-79869134b22d.png)

2022-02-08 14:02 UTC, FlaviaCohen requested changes

2022-02-08 14:02 UTC, FlaviaCohen commented on src/Components/Backoffice/Activities.js
> +  const categoryMock = [
Gabi... lo que tenés que cambiar es el nombre del Mock, no del componente. ActivitiesList estaba bien, categoriesMock debe ser activitiesMock

2022-02-09 14:06 UTC, gabi-dev-tech commented
correccion lista!

2022-02-09 22:19 UTC, FlaviaCohen commented
Solucionar conflictos

2022-02-10 20:48 UTC, silversurferbeats commented
solucion de conflictos.

2022-02-12 00:34 UTC, FlaviaCohen approved these changes

2022-02-12 00:34 UTC, merged