Ot127 70/feat/crear-método-reutilizable-que-realice-una-petición-post-a-los-endpoints-privados-de-la-api
alkemyTech/OT127-CLIENT pull request #86
Opened 2022-02-05 19:21 UTC by silversurferbeats

El método debe recibir una ruta destino, un objeto con estructura de datos para enviar en el BODY, e invocar el método para agregar y encabezado Autorización en base al token del usuario, para generar una petición POST. Agregar a privateApiService.js.

2022-02-07 15:56 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-02-07 15:56 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +export const privateServicePost = (route, data) => {
Llamemoslo privatePost para ser consistentes con los nombres de los otros servicios

2022-02-07 21:58 UTC, silversurferbeats commented on src/Services/privateApiService.js
> +export const privateServicePost = (route, data) => {
Cambio de variable a privatePost:
![image](https://user-images.githubusercontent.com/67937686/152878959-2da52f35-99b2-4aeb-b678-1291074dc00e.png)

2022-02-08 13:58 UTC, FlaviaCohen requested changes

2022-02-08 13:58 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +export const privatePost = (route, data) => {
Gabi, estás pisando el código de Matias que hizo el delete privado. Tenés que hacer uno nuevo, no reemplazar uno que ya está hecho

2022-02-11 11:16 UTC, gabi-dev-tech commented on src/Services/privateApiService.js
> +export const privatePost = (route, data) => {
corregido

2022-02-12 00:32 UTC, FlaviaCohen requested changes

2022-02-12 00:32 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +export const privatePost = (route, data) => {
No está corregido. Seguís pisando el código de Matías.

2022-02-12 15:28 UTC, silversurferbeats commented
Fla habia pisado el "privateDelete", se me paso mala mia.. Confirmame si eso los cambios estarias correctos.

2022-02-12 22:03 UTC, FlaviaCohen requested changes

2022-02-12 22:03 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +  const url = ${route}/${id}
me parece que le borraste los backtips a la ruta. Fijate de envolver esto ${route}/${id} en backtips como estaba originalmente: 

<img width="223" alt="image" src="https://user-images.githubusercontent.com/63516257/153729921-0015aa68-27cb-4ed0-811e-7939accd83b9.png">

2022-02-13 23:14 UTC, silversurferbeats commented on src/Services/privateApiService.js
> +  const url = ${route}/${id}
corregido backtips .

2022-02-14 02:25 UTC, FlaviaCohen approved these changes

2022-02-14 02:25 UTC, merged