OT127-109/Feat/crear-reducer-de-categorias
alkemyTech/OT127-CLIENT pull request #91
Opened 2022-02-06 22:32 UTC by danieldamian09

Estimada, Flavia

Anexo te detallo cado uno de los pasos que realice para crear el reducer:

1. Creación del archivo de categoriesActions con las 3 acciones más el Thunk para posteriormente realizar la llamada a la API
![actions-reducer-alkemy](https://user-images.githubusercontent.com/63797901/152704027-3ac0a5ba-53c1-45bc-aedf-6bcf36ed50b2.png)

2. Creación del archivo categoriesReducer con cada uno de los casos y también  algunas banderas que las puedo aprovechar para mostar componentes de loading
![reducer-redux-alkemy](https://user-images.githubusercontent.com/63797901/152704118-20239fcf-c8cf-4e16-8ec4-c679b39513ba.png)

3. Creación del archivo selectorCategories donde puedo tener como accesos directos a la información y no están en el componente
![selector-redux-alkemy](https://user-images.githubusercontent.com/63797901/152704164-2e82e4ab-85e2-4dc2-8b9f-835ad7135942.png)

4. Implementación en el componente de los selectores, el thunk, y el dispatch, posteriormente puedo hacer el mapeo de la información
![categories-list-redux-alkemy](https://user-images.githubusercontent.com/63797901/152704229-d319fc0a-d595-4136-b357-8bac7e351582.png)

Resultados una vez realizados todos los pasos:
![Captura de pantalla (858)](https://user-images.githubusercontent.com/63797901/152704251-c7f6800f-2eb3-4e35-ad15-9eef5c6
![Captura de pantalla (859)](https://user-images.githubusercontent.com/63797901/152704260-3ea566f8-4442-43e4-8f3a-ee74a6866a1e.png)
a1cb5.png)

*hay algunas variables que no estoy utilizando en el componente, pero posteriormente pueden servir para el tema de loading, spiner o mensajes de error

2022-02-07 13:49 UTC, FlaviaCohen requested changes

2022-02-07 13:49 UTC, FlaviaCohen commented on src/Components/Activities/Activities.js
> +<<<<<<< HEAD
Acá hay un conflicto sin resolver

2022-02-07 13:49 UTC, FlaviaCohen commented on src/Redux/actions/categoriesActions.js
> +	"ERROR_FETCGING_CATEGORIES"
Fetching está mal escrito

2022-02-07 13:49 UTC, FlaviaCohen commented on src/Redux/store/store.js
> +<<<<<<< HEAD
Otro conflicto sin resolver

2022-02-07 13:49 UTC, FlaviaCohen commented on src/Redux/store/store.js
> +<<<<<<< HEAD
Otro conflicto sin resolver

2022-02-07 17:54 UTC, danieldamian09 commented
Estimada, Flavia

Cambie el nombre de errorFetchingCategories y listo los conflictos gracias por ayudarme, después me saltaron nuevamente y ahí si me apareció la opción de aceptar los que vienen

2022-02-08 14:50 UTC, FlaviaCohen approved these changes

2022-02-08 14:50 UTC, merged