OT127-103/Feat/mostrar-errores-peticiones-no-se-realicen-correctamente
alkemyTech/OT127-CLIENT pull request #97
Opened 2022-02-07 21:56 UTC by danieldamian09

Estimada, Flavia

Tuve que renombrar la rama le faltaba la O al comienzo, actualice la alerta con la que creo mi compañero 

![Captura de pantalla (874)](https://user-images.githubusercontent.com/63797901/152878756-4548de2d-5d0e-4205-8129-293b6f958e5a.png)
![Captura de pantalla (873)](https://user-images.githubusercontent.com/63797901/152878768-b41d0e03-a750-4a1d-a6ef-e06c9d63a9cc.png)

2022-02-08 14:45 UTC, FlaviaCohen requested changes

2022-02-08 14:45 UTC, FlaviaCohen commented on src/Components/Contact/Contact.js
> +	const [error, setError] = useState(false);
Estuve revisando las tarjetas siguientes y no hay más tareas sobre hacer llamados. Si te queda tiempo podrás hacer el llamado correspondiente a la API de contactos y así implementar bien el error? Sino lo dejamos así.

2022-02-08 19:32 UTC, danieldamian09 commented on src/Components/Contact/Contact.js
> +	const [error, setError] = useState(false);
@fla arme la logica para traerme la data e hice un filtrado para no guardar todos los contactos que vienen de la API son como 700

2022-02-08 20:13 UTC, danieldamian09 commented
Estimada Flavia 

Realice la  petición HTTP para traer los contactos  y poder mostrar el mensaje de error en caso de que la llamada a la API falle, también hice un filter para traer un número reducido de contactos 

![Captura de pantalla 2022-02-08 162312](https://user-images.githubusercontent.com/63797901/153067906-ff9f76da-2615-46d2-8f69-a14cd916467a.png)
![Captura de pantalla 2022-02-08 162446](https://user-images.githubusercontent.com/63797901/153067939-04de1db7-d5ef-45fe-8109-73345e141087.png)

2022-02-08 23:15 UTC, FlaviaCohen requested changes

2022-02-08 23:15 UTC, FlaviaCohen commented on src/Components/Contact/Contact.js
> +			const contactsAPI = data.data;
Creo que hay una variable de ambiente creada para contactos, ya que la tenemos podemos usarla.

2022-02-08 23:15 UTC, FlaviaCohen commented on src/Components/Contact/Contact.js
> +	const [error, setError] = useState(false);
Perfecto!!

2022-02-08 23:15 UTC, FlaviaCohen commented
Solucionar conflictos

2022-02-08 23:42 UTC, danieldamian09 commented on src/Components/Contact/Contact.js
> +			const contactsAPI = data.data;
@FlaviaCohenvariable de entorno agregada

2022-02-08 23:53 UTC, danieldamian09 commented
@FlaviaCohen  resuelto conflicto y agregada la variable de entorno

2022-02-08 23:59 UTC, danieldamian09 commented
@FlaviaCohen actualizada la variable de entorno en el archivo example

2022-02-09 22:23 UTC, FlaviaCohen requested changes
Solucionar conflictos

2022-02-10 12:34 UTC, danieldamian09 commented
Estimada Flavia resueltos conflictos

2022-02-12 00:37 UTC, FlaviaCohen approved these changes

2022-02-12 00:37 UTC, merged